.TH "_GPU_DEVICE" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_GPU_DEVICE \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "DWORD \fBcb\fP"
.br
.ti -1c
.RI "CHAR \fBDeviceName\fP [32]"
.br
.ti -1c
.RI "CHAR \fBDeviceString\fP [128]"
.br
.ti -1c
.RI "DWORD \fBFlags\fP"
.br
.ti -1c
.RI "RECT \fBrcVirtualScreen\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
