.TH "annexes Directory Reference" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
annexes Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBdoc_html\fP"
.br
.ti -1c
.RI "directory \fBtutoriel\fP"
.br
.ti -1c
.RI "directory \fBxml\fP"
.br
.in -1c
