.TH "annexes/xml Directory Reference" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
annexes/xml Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmain_test1\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmain_test2\&.cpp\fP"
.br
.ti -1c
.RI "file \fBtinyxml2\&.cpp\fP"
.br
.ti -1c
.RI "file \fBtinyxml2\&.h\fP"
.br
.ti -1c
.RI "file \fBXmlWrite\&.hpp\fP"
.br
.in -1c
