.TH "Animation" 3 "Tue Jun 9 2015" "Version 0.53" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Animation \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObject3D\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAnimation\fP (glm::vec3, glm::vec3, glm::vec3, std::string const &)"
.br
.ti -1c
.RI "void \fBinitialize\fP ()"
.br
.ti -1c
.RI "void \fBdraw\fP (gdl::AShader &, gdl::Clock const &)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::string \fBm_path\fP"
.br
.ti -1c
.RI "gdl::Model \fBm_model\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
