.TH "lib/gdl/includes/begin_code.h" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/gdl/includes/begin_code.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_begin_code_h\fP"
.br
.ti -1c
.RI "#define \fBSDL_DEPRECATED\fP"
.br
.ti -1c
.RI "#define \fBDECLSPEC\fP"
.br
.ti -1c
.RI "#define \fBSDLCALL\fP"
.br
.ti -1c
.RI "#define \fBSDL_INLINE\fP   inline"
.br
.ti -1c
.RI "#define \fB__inline__\fP   inline"
.br
.ti -1c
.RI "#define \fBSDL_FORCE_INLINE\fP   static SDL_INLINE"
.br
.ti -1c
.RI "#define \fBNULL\fP   ((\fBvoid\fP *)0)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file sets things up for C dynamic library function definitions, static inlined functions, and structures aligned at 4-byte alignment\&. If you don't like ugly C preprocessor code, don't look at this file\&. :) 
.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
