.TH "BoxBonus" 3 "Tue Jun 9 2015" "Version 0.53" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BoxBonus \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBoxBonus\fP (unsigned int)"
.br
.ti -1c
.RI "\fBAnimation\fP * \fBgetAnimation\fP () const "
.br
.ti -1c
.RI "unsigned int \fBgetPosition\fP ()"
.br
.ti -1c
.RI "std::string \fBgetBonus\fP ()"
.br
.ti -1c
.RI "void \fBsetPosition\fP (unsigned int)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBm_position\fP"
.br
.ti -1c
.RI "std::string \fBm_bonus\fP"
.br
.ti -1c
.RI "\fBAnimation\fP * \fBm_animation\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
