.TH "Camera" 3 "Tue Jun 9 2015" "Version 0.53" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Camera \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "glm::mat4 \fBgetProjection\fP () const "
.br
.ti -1c
.RI "glm::mat4 \fBgetTransformation\fP () const "
.br
.ti -1c
.RI "void \fBsetCamera\fP (glm::vec3 const &, glm::vec3 const &)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBCamera\fP & \fBoperator=\fP (\fBCamera\fP const &)"
.br
.ti -1c
.RI "\fBCamera\fP (\fBCamera\fP const &)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "glm::mat4 \fBm_projection\fP"
.br
.ti -1c
.RI "glm::mat4 \fBm_transformation\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
