.TH "lib/gdl/includes/close_code.h" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/gdl/includes/close_code.h \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
This file reverses the effects of \fBbegin_code\&.h\fP and should be included after you finish any function and structure declarations in your headers 
.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
