.TH "core_precision" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core_precision \- Precision types
.PP
Non-GLSL types that are used to define precision-based types\&.  

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef lowp_float_t \fBglm::lowp_float\fP"
.br
.ti -1c
.RI "typedef mediump_float_t \fBglm::mediump_float\fP"
.br
.ti -1c
.RI "typedef highp_float_t \fBglm::highp_float\fP"
.br
.ti -1c
.RI "typedef mediump_float \fBglm::float_t\fP"
.br
.ti -1c
.RI "typedef detail::lowp_int_t \fBglm::lowp_int\fP"
.br
.ti -1c
.RI "typedef detail::mediump_int_t \fBglm::mediump_int\fP"
.br
.ti -1c
.RI "typedef detail::highp_int_t \fBglm::highp_int\fP"
.br
.ti -1c
.RI "typedef detail::lowp_uint_t \fBglm::lowp_uint\fP"
.br
.ti -1c
.RI "typedef detail::mediump_uint_t \fBglm::mediump_uint\fP"
.br
.ti -1c
.RI "typedef detail::highp_uint_t \fBglm::highp_uint\fP"
.br
.ti -1c
.RI "typedef mediump_int \fBglm::int_t\fP"
.br
.ti -1c
.RI "typedef mediump_uint \fBglm::uint_t\fP"
.br
.ti -1c
.RI "typedef uint_t \fBglm::uint\fP"
.br
.ti -1c
.RI "typedef detail::tmat2x2< lowp_float > \fBglm::lowp_mat2\fP"
.br
.ti -1c
.RI "typedef detail::tmat2x2< mediump_float > \fBglm::mediump_mat2\fP"
.br
.ti -1c
.RI "typedef detail::tmat2x2< highp_float > \fBglm::highp_mat2\fP"
.br
.ti -1c
.RI "typedef detail::tmat2x2< lowp_float > \fBglm::lowp_mat2x2\fP"
.br
.ti -1c
.RI "typedef detail::tmat2x2< mediump_float > \fBglm::mediump_mat2x2\fP"
.br
.ti -1c
.RI "typedef detail::tmat2x2< highp_float > \fBglm::highp_mat2x2\fP"
.br
.ti -1c
.RI "typedef detail::tmat2x3< lowp_float > \fBglm::lowp_mat2x3\fP"
.br
.ti -1c
.RI "typedef detail::tmat2x3< mediump_float > \fBglm::mediump_mat2x3\fP"
.br
.ti -1c
.RI "typedef detail::tmat2x3< highp_float > \fBglm::highp_mat2x3\fP"
.br
.ti -1c
.RI "typedef detail::tmat2x4< lowp_float > \fBglm::lowp_mat2x4\fP"
.br
.ti -1c
.RI "typedef detail::tmat2x4< mediump_float > \fBglm::mediump_mat2x4\fP"
.br
.ti -1c
.RI "typedef detail::tmat2x4< highp_float > \fBglm::highp_mat2x4\fP"
.br
.ti -1c
.RI "typedef detail::tmat3x2< lowp_float > \fBglm::lowp_mat3x2\fP"
.br
.ti -1c
.RI "typedef detail::tmat3x2< mediump_float > \fBglm::mediump_mat3x2\fP"
.br
.ti -1c
.RI "typedef detail::tmat3x2< highp_float > \fBglm::highp_mat3x2\fP"
.br
.ti -1c
.RI "typedef detail::tmat3x3< lowp_float > \fBglm::lowp_mat3\fP"
.br
.ti -1c
.RI "typedef detail::tmat3x3< mediump_float > \fBglm::mediump_mat3\fP"
.br
.ti -1c
.RI "typedef detail::tmat3x3< highp_float > \fBglm::highp_mat3\fP"
.br
.ti -1c
.RI "typedef detail::tmat3x3< lowp_float > \fBglm::lowp_mat3x3\fP"
.br
.ti -1c
.RI "typedef detail::tmat3x3< mediump_float > \fBglm::mediump_mat3x3\fP"
.br
.ti -1c
.RI "typedef detail::tmat3x3< highp_float > \fBglm::highp_mat3x3\fP"
.br
.ti -1c
.RI "typedef detail::tmat3x4< lowp_float > \fBglm::lowp_mat3x4\fP"
.br
.ti -1c
.RI "typedef detail::tmat3x4< mediump_float > \fBglm::mediump_mat3x4\fP"
.br
.ti -1c
.RI "typedef detail::tmat3x4< highp_float > \fBglm::highp_mat3x4\fP"
.br
.ti -1c
.RI "typedef detail::tmat4x2< lowp_float > \fBglm::lowp_mat4x2\fP"
.br
.ti -1c
.RI "typedef detail::tmat4x2< mediump_float > \fBglm::mediump_mat4x2\fP"
.br
.ti -1c
.RI "typedef detail::tmat4x2< highp_float > \fBglm::highp_mat4x2\fP"
.br
.ti -1c
.RI "typedef detail::tmat4x3< lowp_float > \fBglm::lowp_mat4x3\fP"
.br
.ti -1c
.RI "typedef detail::tmat4x3< mediump_float > \fBglm::mediump_mat4x3\fP"
.br
.ti -1c
.RI "typedef detail::tmat4x3< highp_float > \fBglm::highp_mat4x3\fP"
.br
.ti -1c
.RI "typedef detail::tmat4x4< lowp_float > \fBglm::lowp_mat4\fP"
.br
.ti -1c
.RI "typedef detail::tmat4x4< mediump_float > \fBglm::mediump_mat4\fP"
.br
.ti -1c
.RI "typedef detail::tmat4x4< highp_float > \fBglm::highp_mat4\fP"
.br
.ti -1c
.RI "typedef detail::tmat4x4< lowp_float > \fBglm::lowp_mat4x4\fP"
.br
.ti -1c
.RI "typedef detail::tmat4x4< mediump_float > \fBglm::mediump_mat4x4\fP"
.br
.ti -1c
.RI "typedef detail::tmat4x4< highp_float > \fBglm::highp_mat4x4\fP"
.br
.ti -1c
.RI "typedef detail::tvec2< highp_float > \fBglm::highp_vec2\fP"
.br
.ti -1c
.RI "typedef detail::tvec2< mediump_float > \fBglm::mediump_vec2\fP"
.br
.ti -1c
.RI "typedef detail::tvec2< lowp_float > \fBglm::lowp_vec2\fP"
.br
.ti -1c
.RI "typedef detail::tvec2< highp_int > \fBglm::highp_ivec2\fP"
.br
.ti -1c
.RI "typedef detail::tvec2< mediump_int > \fBglm::mediump_ivec2\fP"
.br
.ti -1c
.RI "typedef detail::tvec2< lowp_int > \fBglm::lowp_ivec2\fP"
.br
.ti -1c
.RI "typedef detail::tvec2< highp_uint > \fBglm::highp_uvec2\fP"
.br
.ti -1c
.RI "typedef detail::tvec2< mediump_uint > \fBglm::mediump_uvec2\fP"
.br
.ti -1c
.RI "typedef detail::tvec2< lowp_uint > \fBglm::lowp_uvec2\fP"
.br
.ti -1c
.RI "typedef detail::tvec3< highp_float > \fBglm::highp_vec3\fP"
.br
.ti -1c
.RI "typedef detail::tvec3< mediump_float > \fBglm::mediump_vec3\fP"
.br
.ti -1c
.RI "typedef detail::tvec3< lowp_float > \fBglm::lowp_vec3\fP"
.br
.ti -1c
.RI "typedef detail::tvec3< highp_int > \fBglm::highp_ivec3\fP"
.br
.ti -1c
.RI "typedef detail::tvec3< mediump_int > \fBglm::mediump_ivec3\fP"
.br
.ti -1c
.RI "typedef detail::tvec3< lowp_int > \fBglm::lowp_ivec3\fP"
.br
.ti -1c
.RI "typedef detail::tvec3< highp_uint > \fBglm::highp_uvec3\fP"
.br
.ti -1c
.RI "typedef detail::tvec3< mediump_uint > \fBglm::mediump_uvec3\fP"
.br
.ti -1c
.RI "typedef detail::tvec3< lowp_uint > \fBglm::lowp_uvec3\fP"
.br
.ti -1c
.RI "typedef detail::tvec4< highp_float > \fBglm::highp_vec4\fP"
.br
.ti -1c
.RI "typedef detail::tvec4< mediump_float > \fBglm::mediump_vec4\fP"
.br
.ti -1c
.RI "typedef detail::tvec4< lowp_float > \fBglm::lowp_vec4\fP"
.br
.ti -1c
.RI "typedef detail::tvec4< highp_int > \fBglm::highp_ivec4\fP"
.br
.ti -1c
.RI "typedef detail::tvec4< mediump_int > \fBglm::mediump_ivec4\fP"
.br
.ti -1c
.RI "typedef detail::tvec4< lowp_int > \fBglm::lowp_ivec4\fP"
.br
.ti -1c
.RI "typedef detail::tvec4< highp_uint > \fBglm::highp_uvec4\fP"
.br
.ti -1c
.RI "typedef detail::tvec4< mediump_uint > \fBglm::mediump_uvec4\fP"
.br
.ti -1c
.RI "typedef detail::tvec4< lowp_uint > \fBglm::lowp_uvec4\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Non-GLSL types that are used to define precision-based types\&. 

The GLSL language allows the user to define the precision of a particular variable\&. In OpenGL's GLSL, these precision qualifiers have no effect; they are there for compatibility with OpenGL ES's precision qualifiers, where they \fIdo\fP have an effect\&.
.PP
C++ has no language equivalent to precision qualifiers\&. So GLM provides the next-best thing: a number of typedefs of the \fBTemplate types\fP that use a particular precision\&.
.PP
None of these types make any guarantees about the actual precision used\&. 
.SH "Typedef Documentation"
.PP 
.SS "typedef highp_float_t \fBglm::highp_float\fP"
High precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.4 Floats\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::highp_int_t \fBglm::highp_int\fP"
High precision signed integer\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.3 Integers\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tvec2<highp_int> \fBglm::highp_ivec2\fP"
2 components vector of high precision signed integer numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tvec3<highp_int> \fBglm::highp_ivec3\fP"
3 components vector of high precision signed integer numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tvec4<highp_int> \fBglm::highp_ivec4\fP"
4 components vector of high precision signed integer numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tmat2x2<highp_float> \fBglm::highp_mat2\fP"
2 columns of 2 components matrix of high precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tmat2x2<highp_float> \fBglm::highp_mat2x2\fP"
2 columns of 2 components matrix of high precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tmat2x3<highp_float> \fBglm::highp_mat2x3\fP"
2 columns of 3 components matrix of high precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tmat2x4<highp_float> \fBglm::highp_mat2x4\fP"
2 columns of 4 components matrix of high precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tmat3x3<highp_float> \fBglm::highp_mat3\fP"
3 columns of 3 components matrix of high precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tmat3x2<highp_float> \fBglm::highp_mat3x2\fP"
3 columns of 2 components matrix of high precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tmat3x3<highp_float> \fBglm::highp_mat3x3\fP"
3 columns of 3 components matrix of high precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tmat3x4<highp_float> \fBglm::highp_mat3x4\fP"
3 columns of 4 components matrix of high precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tmat4x4<highp_float> \fBglm::highp_mat4\fP"
4 columns of 4 components matrix of high precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tmat4x2<highp_float> \fBglm::highp_mat4x2\fP"
4 columns of 2 components matrix of high precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tmat4x3<highp_float> \fBglm::highp_mat4x3\fP"
4 columns of 3 components matrix of high precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tmat4x4<highp_float> \fBglm::highp_mat4x4\fP"
4 columns of 4 components matrix of high precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::highp_uint_t \fBglm::highp_uint\fP"
High precision unsigned integer\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.3 Integers\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tvec2<highp_uint> \fBglm::highp_uvec2\fP"
2 components vector of high precision unsigned integer numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tvec3<highp_uint> \fBglm::highp_uvec3\fP"
3 components vector of high precision unsigned integer numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tvec4<highp_uint> \fBglm::highp_uvec4\fP"
4 components vector of high precision unsigned integer numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tvec2<highp_float> \fBglm::highp_vec2\fP"
2 components vector of high precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tvec3<highp_float> \fBglm::highp_vec3\fP"
3 components vector of high precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tvec4<highp_float> \fBglm::highp_vec4\fP"
4 components vector of high precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef lowp_float_t \fBglm::lowp_float\fP"
Low precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.4 Floats\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::lowp_int_t \fBglm::lowp_int\fP"
Low precision signed integer\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.3 Integers\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tvec2<lowp_int> \fBglm::lowp_ivec2\fP"
2 components vector of low precision signed integer numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tvec3<lowp_int> \fBglm::lowp_ivec3\fP"
3 components vector of low precision signed integer numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tvec4<lowp_int> \fBglm::lowp_ivec4\fP"
4 components vector of low precision signed integer numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tmat2x2<lowp_float> \fBglm::lowp_mat2\fP"
2 columns of 2 components matrix of low precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tmat2x2<lowp_float> \fBglm::lowp_mat2x2\fP"
2 columns of 2 components matrix of low precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tmat2x3<lowp_float> \fBglm::lowp_mat2x3\fP"
2 columns of 3 components matrix of low precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tmat2x4<lowp_float> \fBglm::lowp_mat2x4\fP"
2 columns of 4 components matrix of low precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tmat3x3<lowp_float> \fBglm::lowp_mat3\fP"
3 columns of 3 components matrix of low precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tmat3x2<lowp_float> \fBglm::lowp_mat3x2\fP"
3 columns of 2 components matrix of low precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tmat3x3<lowp_float> \fBglm::lowp_mat3x3\fP"
3 columns of 3 components matrix of low precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tmat3x4<lowp_float> \fBglm::lowp_mat3x4\fP"
3 columns of 4 components matrix of low precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tmat4x4<lowp_float> \fBglm::lowp_mat4\fP"
4 columns of 4 components matrix of low precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tmat4x2<lowp_float> \fBglm::lowp_mat4x2\fP"
4 columns of 2 components matrix of low precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tmat4x3<lowp_float> \fBglm::lowp_mat4x3\fP"
4 columns of 3 components matrix of low precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tmat4x4<lowp_float> \fBglm::lowp_mat4x4\fP"
4 columns of 4 components matrix of low precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::lowp_uint_t \fBglm::lowp_uint\fP"
Low precision unsigned integer\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.3 Integers\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tvec2<lowp_uint> \fBglm::lowp_uvec2\fP"
2 components vector of low precision unsigned integer numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tvec3<lowp_uint> \fBglm::lowp_uvec3\fP"
3 components vector of low precision unsigned integer numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tvec4<lowp_uint> \fBglm::lowp_uvec4\fP"
4 components vector of low precision unsigned integer numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tvec2<lowp_float> \fBglm::lowp_vec2\fP"
2 components vector of low precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tvec3<lowp_float> \fBglm::lowp_vec3\fP"
3 components vector of low precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tvec4<lowp_float> \fBglm::lowp_vec4\fP"
4 components vector of low precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef mediump_float_t \fBglm::mediump_float\fP"
Medium precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.4 Floats\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::mediump_int_t \fBglm::mediump_int\fP"
Medium precision signed integer\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.3 Integers\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tvec2<mediump_int> \fBglm::mediump_ivec2\fP"
2 components vector of medium precision signed integer numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tvec3<mediump_int> \fBglm::mediump_ivec3\fP"
3 components vector of medium precision signed integer numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tvec4<mediump_int> \fBglm::mediump_ivec4\fP"
4 components vector of medium precision signed integer numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tmat2x2<mediump_float> \fBglm::mediump_mat2\fP"
2 columns of 2 components matrix of medium precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tmat2x2<mediump_float> \fBglm::mediump_mat2x2\fP"
2 columns of 2 components matrix of medium precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tmat2x3<mediump_float> \fBglm::mediump_mat2x3\fP"
2 columns of 3 components matrix of medium precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tmat2x4<mediump_float> \fBglm::mediump_mat2x4\fP"
2 columns of 4 components matrix of medium precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tmat3x3<mediump_float> \fBglm::mediump_mat3\fP"
3 columns of 3 components matrix of medium precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tmat3x2<mediump_float> \fBglm::mediump_mat3x2\fP"
3 columns of 2 components matrix of medium precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tmat3x3<mediump_float> \fBglm::mediump_mat3x3\fP"
3 columns of 3 components matrix of medium precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tmat3x4<mediump_float> \fBglm::mediump_mat3x4\fP"
3 columns of 4 components matrix of medium precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tmat4x4<mediump_float> \fBglm::mediump_mat4\fP"
4 columns of 4 components matrix of medium precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tmat4x2<mediump_float> \fBglm::mediump_mat4x2\fP"
4 columns of 2 components matrix of medium precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tmat4x3<mediump_float> \fBglm::mediump_mat4x3\fP"
4 columns of 3 components matrix of medium precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tmat4x4<mediump_float> \fBglm::mediump_mat4x4\fP"
4 columns of 4 components matrix of medium precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::mediump_uint_t \fBglm::mediump_uint\fP"
Medium precision unsigned integer\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.3 Integers\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tvec2<mediump_uint> \fBglm::mediump_uvec2\fP"
2 components vector of medium precision unsigned integer numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tvec3<mediump_uint> \fBglm::mediump_uvec3\fP"
3 components vector of medium precision unsigned integer numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tvec4<mediump_uint> \fBglm::mediump_uvec4\fP"
4 components vector of medium precision unsigned integer numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tvec2<mediump_float> \fBglm::mediump_vec2\fP"
2 components vector of medium precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tvec3<mediump_float> \fBglm::mediump_vec3\fP"
3 components vector of medium precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef detail::tvec4<mediump_float> \fBglm::mediump_vec4\fP"
4 components vector of medium precision floating-point numbers\&. There is no guarantee on the actual precision\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.PP
\fCGLSL 4\&.20\&.8 specification, section 4\&.7\&.2 Precision Qualifier\fP 
.RE
.PP

.SS "typedef uint_t \fBglm::uint\fP"
Unsigned integer type\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.3 Integers\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
