.TH "core_types" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core_types \- Types
.PP
The standard types defined by the specification\&.  

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef mediump_vec2 \fBglm::vec2\fP"
.br
.ti -1c
.RI "typedef mediump_vec3 \fBglm::vec3\fP"
.br
.ti -1c
.RI "typedef mediump_vec4 \fBglm::vec4\fP"
.br
.ti -1c
.RI "typedef mediump_mat2x2 \fBglm::mat2x2\fP"
.br
.ti -1c
.RI "typedef mediump_mat2x3 \fBglm::mat2x3\fP"
.br
.ti -1c
.RI "typedef mediump_mat2x4 \fBglm::mat2x4\fP"
.br
.ti -1c
.RI "typedef mediump_mat3x2 \fBglm::mat3x2\fP"
.br
.ti -1c
.RI "typedef mediump_mat3x3 \fBglm::mat3x3\fP"
.br
.ti -1c
.RI "typedef mediump_mat3x4 \fBglm::mat3x4\fP"
.br
.ti -1c
.RI "typedef mediump_mat4x2 \fBglm::mat4x2\fP"
.br
.ti -1c
.RI "typedef mediump_mat4x3 \fBglm::mat4x3\fP"
.br
.ti -1c
.RI "typedef mediump_mat4x4 \fBglm::mat4x4\fP"
.br
.ti -1c
.RI "typedef mat2x2 \fBglm::mat2\fP"
.br
.ti -1c
.RI "typedef mat3x3 \fBglm::mat3\fP"
.br
.ti -1c
.RI "typedef mat4x4 \fBglm::mat4\fP"
.br
.ti -1c
.RI "typedef mediump_ivec2 \fBglm::ivec2\fP"
.br
.ti -1c
.RI "typedef mediump_ivec3 \fBglm::ivec3\fP"
.br
.ti -1c
.RI "typedef mediump_ivec4 \fBglm::ivec4\fP"
.br
.ti -1c
.RI "typedef mediump_uvec2 \fBglm::uvec2\fP"
.br
.ti -1c
.RI "typedef mediump_uvec3 \fBglm::uvec3\fP"
.br
.ti -1c
.RI "typedef mediump_uvec4 \fBglm::uvec4\fP"
.br
.ti -1c
.RI "typedef detail::tvec2< bool > \fBglm::bvec2\fP"
.br
.ti -1c
.RI "typedef detail::tvec3< bool > \fBglm::bvec3\fP"
.br
.ti -1c
.RI "typedef detail::tvec4< bool > \fBglm::bvec4\fP"
.br
.ti -1c
.RI "typedef detail::tvec2< double > \fBglm::dvec2\fP"
.br
.ti -1c
.RI "typedef detail::tvec3< double > \fBglm::dvec3\fP"
.br
.ti -1c
.RI "typedef detail::tvec4< double > \fBglm::dvec4\fP"
.br
.ti -1c
.RI "typedef detail::tmat2x2< double > \fBglm::dmat2\fP"
.br
.ti -1c
.RI "typedef detail::tmat3x3< double > \fBglm::dmat3\fP"
.br
.ti -1c
.RI "typedef detail::tmat4x4< double > \fBglm::dmat4\fP"
.br
.ti -1c
.RI "typedef detail::tmat2x2< double > \fBglm::dmat2x2\fP"
.br
.ti -1c
.RI "typedef detail::tmat2x3< double > \fBglm::dmat2x3\fP"
.br
.ti -1c
.RI "typedef detail::tmat2x4< double > \fBglm::dmat2x4\fP"
.br
.ti -1c
.RI "typedef detail::tmat3x2< double > \fBglm::dmat3x2\fP"
.br
.ti -1c
.RI "typedef detail::tmat3x3< double > \fBglm::dmat3x3\fP"
.br
.ti -1c
.RI "typedef detail::tmat3x4< double > \fBglm::dmat3x4\fP"
.br
.ti -1c
.RI "typedef detail::tmat4x2< double > \fBglm::dmat4x2\fP"
.br
.ti -1c
.RI "typedef detail::tmat4x3< double > \fBglm::dmat4x3\fP"
.br
.ti -1c
.RI "typedef detail::tmat4x4< double > \fBglm::dmat4x4\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The standard types defined by the specification\&. 

These types are all typedefs of more generalized, template types\&. To see the definiton of these template types, go to \fBTemplate types\fP\&. 
.SH "Typedef Documentation"
.PP 
.SS "typedef detail::tvec2<bool> \fBglm::bvec2\fP"
2 components vector of boolean\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.RE
.PP

.SS "typedef detail::tvec3<bool> \fBglm::bvec3\fP"
3 components vector of boolean\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.RE
.PP

.SS "typedef detail::tvec4<bool> \fBglm::bvec4\fP"
4 components vector of boolean\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.RE
.PP

.SS "typedef detail::tmat2x2<double> \fBglm::dmat2\fP"
2 * 2 matrix of double-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef detail::tmat2x2<double> \fBglm::dmat2x2\fP"
2 * 2 matrix of double-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef detail::tmat2x3<double> \fBglm::dmat2x3\fP"
2 * 3 matrix of double-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef detail::tmat2x4<double> \fBglm::dmat2x4\fP"
2 * 4 matrix of double-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef detail::tmat3x3<double> \fBglm::dmat3\fP"
3 * 3 matrix of double-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef detail::tmat3x2<double> \fBglm::dmat3x2\fP"
3 * 2 matrix of double-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef detail::tmat3x3<double> \fBglm::dmat3x3\fP"
3 * 3 matrix of double-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef detail::tmat3x4<double> \fBglm::dmat3x4\fP"
3 * 4 matrix of double-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef detail::tmat4x4<double> \fBglm::dmat4\fP"
4 * 4 matrix of double-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef detail::tmat4x2<double> \fBglm::dmat4x2\fP"
4 * 2 matrix of double-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef detail::tmat4x3<double> \fBglm::dmat4x3\fP"
4 * 3 matrix of double-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef detail::tmat4x4<double> \fBglm::dmat4x4\fP"
4 * 4 matrix of double-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef detail::tvec2<double> \fBglm::dvec2\fP"
Vector of 2 double-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.RE
.PP

.SS "typedef detail::tvec3<double> \fBglm::dvec3\fP"
Vector of 3 double-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.RE
.PP

.SS "typedef detail::tvec4<double> \fBglm::dvec4\fP"
Vector of 4 double-precision floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.RE
.PP

.SS "typedef mediump_ivec2 \fBglm::ivec2\fP"
2 components vector of signed integer numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.RE
.PP

.SS "typedef mediump_ivec3 \fBglm::ivec3\fP"
3 components vector of signed integer numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.RE
.PP

.SS "typedef mediump_ivec4 \fBglm::ivec4\fP"
4 components vector of signed integer numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.RE
.PP

.SS "typedef mat2x2 \fBglm::mat2\fP"
2 columns of 2 components matrix of floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef mediump_mat2x2 \fBglm::mat2x2\fP"
2 columns of 2 components matrix of floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef mediump_mat2x3 \fBglm::mat2x3\fP"
2 columns of 3 components matrix of floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef mediump_mat2x4 \fBglm::mat2x4\fP"
2 columns of 4 components matrix of floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef mat3x3 \fBglm::mat3\fP"
3 columns of 3 components matrix of floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef mediump_mat3x2 \fBglm::mat3x2\fP"
3 columns of 2 components matrix of floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef mediump_mat3x3 \fBglm::mat3x3\fP"
3 columns of 3 components matrix of floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef mediump_mat3x4 \fBglm::mat3x4\fP"
3 columns of 4 components matrix of floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef mat4x4 \fBglm::mat4\fP"
4 columns of 4 components matrix of floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef mediump_mat4x2 \fBglm::mat4x2\fP"
4 columns of 2 components matrix of floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef mediump_mat4x3 \fBglm::mat4x3\fP"
4 columns of 3 components matrix of floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef mediump_mat4x4 \fBglm::mat4x4\fP"
4 columns of 4 components matrix of floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.6 Matrices\fP 
.RE
.PP

.SS "typedef mediump_uvec2 \fBglm::uvec2\fP"
2 components vector of unsigned integer numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.RE
.PP

.SS "typedef mediump_uvec3 \fBglm::uvec3\fP"
3 components vector of unsigned integer numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.RE
.PP

.SS "typedef mediump_uvec4 \fBglm::uvec4\fP"
4 components vector of unsigned integer numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.RE
.PP

.SS "typedef mediump_vec2 \fBglm::vec2\fP"
2 components vector of floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.RE
.PP

.SS "typedef mediump_vec3 \fBglm::vec3\fP"
3 components vector of floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.RE
.PP

.SS "typedef mediump_vec4 \fBglm::vec4\fP"
4 components vector of floating-point numbers\&.
.PP
\fBSee also:\fP
.RS 4
\fCGLSL 4\&.20\&.8 specification, section 4\&.1\&.5 Vectors\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
