.TH "Cube" 3 "Tue Jun 9 2015" "Version 0.53" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cube \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBinitialize\fP ()"
.br
.ti -1c
.RI "virtual void \fBupdate\fP (gdl::Clock const &clock, gdl::Input &input)"
.br
.ti -1c
.RI "virtual void \fBdraw\fP (gdl::AShader &shader, gdl::Clock const &clock)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "gdl::Texture \fB_texture\fP"
.br
.ti -1c
.RI "gdl::Geometry \fB_geometry\fP"
.br
.ti -1c
.RI "float \fB_speed\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
