.TH "ErrorBomberman" 3 "Tue Jun 9 2015" "Version 0.53" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ErrorBomberman \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBErrorBomberman\fP (std::string const &message, std::string const &component='Unknown')"
.br
.ti -1c
.RI "std::string const & \fBgetComponent\fP () const "
.br
.ti -1c
.RI "const char * \fBwhat\fP () const   throw ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::string \fBm_component\fP"
.br
.ti -1c
.RI "std::string \fBm_message\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
