.TH "gdl::IRenderContext" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gdl::IRenderContext \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBgdl::SdlContext\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBstart\fP (unsigned \fBint\fP swidth, unsigned \fBint\fP sheight, const std::string &name, \fBint\fP initFlags, \fBint\fP windowsFlags)=0"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBupdateInputs\fP (\fBInput\fP &input) const =0"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBupdateClock\fP (\fBClock\fP &clock) const =0"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBflush\fP () const =0"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBstop\fP () const =0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
