.TH "gdl::Clock" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gdl::Clock \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBupdate\fP (unsigned \fBint\fP currentTime)"
.br
.ti -1c
.RI "double \fBgetElapsed\fP () const "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBint\fP \fB_oldTime\fP"
.br
.ti -1c
.RI "unsigned \fBint\fP \fB_curTime\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
