.TH "gdl::Game" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gdl::Game \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBGameEngine\fP, and \fBGameEngine\fP\fC [private]\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBinitialize\fP ()=0"
.br
.ti -1c
.RI "virtual bool \fBupdate\fP ()=0"
.br
.ti -1c
.RI "virtual \fBvoid\fP \fBdraw\fP ()=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
