.TH "gdl::Attribute" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gdl::Attribute \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAttribute\fP (size_t nbrByte, size_t nbrComponent, GLenum type)"
.br
.ti -1c
.RI "\fBAttribute\fP (\fBAttribute\fP const &copy)"
.br
.ti -1c
.RI "\fBAttribute\fP & \fBoperator=\fP (\fBAttribute\fP const &r)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBnbrByte\fP"
.br
.ti -1c
.RI "size_t \fBnbrComponent\fP"
.br
.ti -1c
.RI "size_t \fBoffset\fP"
.br
.ti -1c
.RI "GLenum \fBtype\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
