.TH "gdl::BasicShader" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gdl::BasicShader \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgdl::AShader\fP, and \fBgdl::AShader\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBbuild\fP ()"
.br
.ti -1c
.RI "virtual bool \fBbuild\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
