.TH "include/GenerateMaze.hh" 3 "Tue Jun 9 2015" "Version 0.53" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/GenerateMaze.hh \- create map (random or not)  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <random>\fP
.br
\fC#include <list>\fP
.br
\fC#include <map>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGenerateMaze\fP"
.br
.RI "\fIGenerate maze (char *) \fP"
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBID_EMPTY\fP   48"
.br
.ti -1c
.RI "#define \fBID_WALL\fP   49"
.br
.ti -1c
.RI "#define \fBID_BOMB\fP   50"
.br
.ti -1c
.RI "#define \fBID_PLAYER\fP   51"
.br
.ti -1c
.RI "#define \fBID_BLOCK\fP   52"
.br
.ti -1c
.RI "#define \fBID_PLAYER_BOMB\fP   53"
.br
.ti -1c
.RI "#define \fBCASE\fP   1\&.0"
.br
.in -1c
.SH "Detailed Description"
.PP 
create map (random or not) 


.PP
\fBAuthor:\fP
.RS 4
ankirama 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.01 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
