.TH "include/GenerateText.hh" 3 "Tue Jun 9 2015" "Version 0.53" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/GenerateText.hh \- display text GUI  

.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include 'Object2D\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGenerateText\fP"
.br
.RI "\fIDisplay text on screen\&. \fP"
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPATH_TXT_NORMAL\fP(c)   (std::string(IMG_PATH) + std::string('alphanumeric/') + std::string(c) + std::string('\&.tga'))"
.br
.ti -1c
.RI "#define \fBPATH_TXT_ORANGE\fP(c)   (std::string(IMG_PATH) + std::string('alphanumeric_orange/') + std::string(c) + std::string('\&.tga'))"
.br
.in -1c
.SH "Detailed Description"
.PP 
display text GUI 


.PP
\fBAuthor:\fP
.RS 4
ankirama 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
