.TH "glm::detail::_swizzle_base1< T, V, E0, E1,-1,-2, 2 >" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::detail::_swizzle_base1< T, V, E0, E1,-1,-2, 2 > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBglm::detail::_swizzle_base0< T, 2 >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "V \fBoperator()\fP () const "
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
