.TH "glm::detail::_swizzle_base2< ValueType, VecType, N, E0, E1, E2, E3, DUPLICATE_ELEMENTS >" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::detail::_swizzle_base2< ValueType, VecType, N, E0, E1, E2, E3, DUPLICATE_ELEMENTS > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBglm::detail::_swizzle_base1< ValueType, VecType, E0, E1, E2, E3, N >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef VecType \fBvec_type\fP"
.br
.ti -1c
.RI "typedef ValueType \fBvalue_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB_swizzle_base2\fP & \fBoperator=\fP (const ValueType &t)"
.br
.ti -1c
.RI "\fB_swizzle_base2\fP & \fBoperator=\fP (const VecType &that)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator-=\fP (const VecType &that)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator+=\fP (const VecType &that)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator*=\fP (const VecType &that)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator/=\fP (const VecType &that)"
.br
.ti -1c
.RI "value_type & \fBoperator[]\fP (size_t i)"
.br
.ti -1c
.RI "value_type \fBoperator[]\fP (size_t i) const "
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "template<typename T > \fBvoid\fP \fB_apply_op\fP (const VecType &that, T op)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
