.TH "glm::detail::uif32" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::detail::uif32 \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "GLM_FUNC_QUALIFIER \fBuif32\fP (float f)"
.br
.ti -1c
.RI "GLM_FUNC_QUALIFIER \fBuif32\fP (unsigned \fBint\fP i)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBf\fP"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBi\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
