.TH "glm::detail::tref4< T >" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::detail::tref4< T > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "GLM_FUNC_DECL \fBtref4\fP (T &x, T &y, T &z, T &w)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBtref4\fP (\fBtref4\fP< T > const &r)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBtref4\fP (\fBtvec4\fP< T > const &v)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBtref4\fP< T > & \fBoperator=\fP (\fBtref4\fP< T > const &r)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBtref4\fP< T > & \fBoperator=\fP (\fBtvec4\fP< T > const &v)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBtvec4\fP< T > \fBoperator()\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T & \fBx\fP"
.br
.ti -1c
.RI "T & \fBy\fP"
.br
.ti -1c
.RI "T & \fBz\fP"
.br
.ti -1c
.RI "T & \fBw\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
