.TH "glm::detail::ieee754_QNAN::i" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::detail::ieee754_QNAN::i \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const unsigned \fBint\fP \fBmantissa\fP:23"
.br
.ti -1c
.RI "const unsigned \fBint\fP \fBexp\fP:8"
.br
.ti -1c
.RI "const unsigned \fBint\fP \fBsign\fP:1"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
