.TH "glm::detail::half" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::detail::half \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "GLM_FUNC_DECL \fBhalf\fP (\fBhalf\fP const &s)"
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_DECL \fBhalf\fP (U const &s)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBoperator float\fP () const "
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBhalf\fP & \fBoperator=\fP (\fBhalf\fP const &s)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBhalf\fP & \fBoperator+=\fP (\fBhalf\fP const &s)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBhalf\fP & \fBoperator-=\fP (\fBhalf\fP const &s)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBhalf\fP & \fBoperator*=\fP (\fBhalf\fP const &s)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBhalf\fP & \fBoperator/=\fP (\fBhalf\fP const &s)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBhalf\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBhalf\fP & \fBoperator--\fP ()"
.br
.ti -1c
.RI "GLM_FUNC_DECL float \fBtoFloat\fP () const "
.br
.ti -1c
.RI "GLM_FUNC_DECL hdata \fB_data\fP () const "
.br
.ti -1c
.RI "template<typename U > GLM_FUNC_QUALIFIER \fBhalf\fP (U const &s)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "hdata \fBdata\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
