.TH "glm::detail::type< T >" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::detail::type< T > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBtype_enum\fP { \fBis_float\fP = is_float<T>::_YES, \fBis_int\fP = is_int<T>::_YES, \fBis_uint\fP = is_uint<T>::_YES, \fBis_bool\fP = is_bool<T>::_YES }"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
