.TH "glm::detail::uif64" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::detail::uif64 \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "GLM_FUNC_QUALIFIER \fBuif64\fP (double f)"
.br
.ti -1c
.RI "GLM_FUNC_QUALIFIER \fBuif64\fP (uint64 i)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBf\fP"
.br
.ti -1c
.RI "uint64 \fBi\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
