.TH "glm::detail::tref1< T >" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::detail::tref1< T > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "GLM_FUNC_DECL \fBtref1\fP (T &x)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBtref1\fP (\fBtref1\fP< T > const &r)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBtref1\fP (\fBtvec1\fP< T > const &v)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBtref1\fP< T > & \fBoperator=\fP (\fBtref1\fP< T > const &r)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBtref1\fP< T > & \fBoperator=\fP (\fBtvec1\fP< T > const &v)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T & \fBx\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
