.TH "GLXPipeRectLimits" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXPipeRectLimits \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBpipeName\fP [GLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX]"
.br
.ti -1c
.RI "\fBint\fP \fBXOrigin\fP"
.br
.ti -1c
.RI "\fBint\fP \fBYOrigin\fP"
.br
.ti -1c
.RI "\fBint\fP \fBmaxHeight\fP"
.br
.ti -1c
.RI "\fBint\fP \fBmaxWidth\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
