.TH "GLXPipeRect" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXPipeRect \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBpipeName\fP [GLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX]"
.br
.ti -1c
.RI "\fBint\fP \fBsrcXOrigin\fP"
.br
.ti -1c
.RI "\fBint\fP \fBsrcYOrigin\fP"
.br
.ti -1c
.RI "\fBint\fP \fBsrcWidth\fP"
.br
.ti -1c
.RI "\fBint\fP \fBsrcHeight\fP"
.br
.ti -1c
.RI "\fBint\fP \fBdestXOrigin\fP"
.br
.ti -1c
.RI "\fBint\fP \fBdestYOrigin\fP"
.br
.ti -1c
.RI "\fBint\fP \fBdestWidth\fP"
.br
.ti -1c
.RI "\fBint\fP \fBdestHeight\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
