.TH "GLXPbufferClobberEvent" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GLXPbufferClobberEvent \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint\fP \fBevent_type\fP"
.br
.ti -1c
.RI "\fBint\fP \fBdraw_type\fP"
.br
.ti -1c
.RI "unsigned long \fBserial\fP"
.br
.ti -1c
.RI "Bool \fBsend_event\fP"
.br
.ti -1c
.RI "Display * \fBdisplay\fP"
.br
.ti -1c
.RI "GLXDrawable \fBdrawable\fP"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBbuffer_mask\fP"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBaux_buffer\fP"
.br
.ti -1c
.RI "\fBint\fP \fBx\fP"
.br
.ti -1c
.RI "\fBint\fP \fBy\fP"
.br
.ti -1c
.RI "\fBint\fP \fBwidth\fP"
.br
.ti -1c
.RI "\fBint\fP \fBheight\fP"
.br
.ti -1c
.RI "\fBint\fP \fBcount\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
