.TH "gtc_half_float" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtc_half_float \- GLM_GTC_half_float
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef detail::half \fBglm::half\fP"
.br
.ti -1c
.RI "typedef detail::tvec2< detail::half > \fBglm::hvec2\fP"
.br
.ti -1c
.RI "typedef detail::tvec3< detail::half > \fBglm::hvec3\fP"
.br
.ti -1c
.RI "typedef detail::tvec4< detail::half > \fBglm::hvec4\fP"
.br
.ti -1c
.RI "typedef detail::tmat2x2< detail::half > \fBglm::hmat2\fP"
.br
.ti -1c
.RI "typedef detail::tmat3x3< detail::half > \fBglm::hmat3\fP"
.br
.ti -1c
.RI "typedef detail::tmat4x4< detail::half > \fBglm::hmat4\fP"
.br
.ti -1c
.RI "typedef detail::tmat2x2< detail::half > \fBglm::hmat2x2\fP"
.br
.ti -1c
.RI "typedef detail::tmat2x3< detail::half > \fBglm::hmat2x3\fP"
.br
.ti -1c
.RI "typedef detail::tmat2x4< detail::half > \fBglm::hmat2x4\fP"
.br
.ti -1c
.RI "typedef detail::tmat3x2< detail::half > \fBglm::hmat3x2\fP"
.br
.ti -1c
.RI "typedef detail::tmat3x3< detail::half > \fBglm::hmat3x3\fP"
.br
.ti -1c
.RI "typedef detail::tmat3x4< detail::half > \fBglm::hmat3x4\fP"
.br
.ti -1c
.RI "typedef detail::tmat4x2< detail::half > \fBglm::hmat4x2\fP"
.br
.ti -1c
.RI "typedef detail::tmat4x3< detail::half > \fBglm::hmat4x3\fP"
.br
.ti -1c
.RI "typedef detail::tmat4x4< detail::half > \fBglm::hmat4x4\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "GLM_FUNC_DECL half \fBglm::abs\fP (half const &x)"
.br
.ti -1c
.RI "GLM_FUNC_DECL hvec2 \fBglm::abs\fP (hvec2 const &x)"
.br
.ti -1c
.RI "GLM_FUNC_DECL hvec3 \fBglm::abs\fP (hvec3 const &x)"
.br
.ti -1c
.RI "GLM_FUNC_DECL hvec4 \fBglm::abs\fP (hvec4 const &x)"
.br
.ti -1c
.RI "GLM_FUNC_DECL half \fBglm::mix\fP (half const &x, half const &y, bool const &a)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines the half-precision floating-point type, along with various typedefs for vectors and matrices\&. <\fBglm/gtc/half_float\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Typedef Documentation"
.PP 
.SS "typedef detail::half \fBglm::half\fP"
Type for half-precision floating-point numbers\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_half_float\fP 
.RE
.PP

.SS "typedef detail::tmat2x2<detail::half> \fBglm::hmat2\fP"
2 * 2 matrix of half-precision floating-point numbers\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_half_float\fP 
.RE
.PP

.SS "typedef detail::tmat2x2<detail::half> \fBglm::hmat2x2\fP"
2 * 2 matrix of half-precision floating-point numbers\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_half_float\fP 
.RE
.PP

.SS "typedef detail::tmat2x3<detail::half> \fBglm::hmat2x3\fP"
2 * 3 matrix of half-precision floating-point numbers\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_half_float\fP 
.RE
.PP

.SS "typedef detail::tmat2x4<detail::half> \fBglm::hmat2x4\fP"
2 * 4 matrix of half-precision floating-point numbers\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_half_float\fP 
.RE
.PP

.SS "typedef detail::tmat3x3<detail::half> \fBglm::hmat3\fP"
3 * 3 matrix of half-precision floating-point numbers\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_half_float\fP 
.RE
.PP

.SS "typedef detail::tmat3x2<detail::half> \fBglm::hmat3x2\fP"
3 * 2 matrix of half-precision floating-point numbers\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_half_float\fP 
.RE
.PP

.SS "typedef detail::tmat3x3<detail::half> \fBglm::hmat3x3\fP"
3 * 3 matrix of half-precision floating-point numbers\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_half_float\fP 
.RE
.PP

.SS "typedef detail::tmat3x4<detail::half> \fBglm::hmat3x4\fP"
3 * 4 matrix of half-precision floating-point numbers\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_half_float\fP 
.RE
.PP

.SS "typedef detail::tmat4x4<detail::half> \fBglm::hmat4\fP"
4 * 4 matrix of half-precision floating-point numbers\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_half_float\fP 
.RE
.PP

.SS "typedef detail::tmat4x2<detail::half> \fBglm::hmat4x2\fP"
4 * 2 matrix of half-precision floating-point numbers\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_half_float\fP 
.RE
.PP

.SS "typedef detail::tmat4x3<detail::half> \fBglm::hmat4x3\fP"
4 * 3 matrix of half-precision floating-point numbers\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_half_float\fP 
.RE
.PP

.SS "typedef detail::tmat4x4<detail::half> \fBglm::hmat4x4\fP"
4 * 4 matrix of half-precision floating-point numbers\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_half_float\fP 
.RE
.PP

.SS "typedef detail::tvec2<detail::half> \fBglm::hvec2\fP"
Vector of 2 half-precision floating-point numbers\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_half_float\fP 
.RE
.PP

.SS "typedef detail::tvec3<detail::half> \fBglm::hvec3\fP"
Vector of 3 half-precision floating-point numbers\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_half_float\fP 
.RE
.PP

.SS "typedef detail::tvec4<detail::half> \fBglm::hvec4\fP"
Vector of 4 half-precision floating-point numbers\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_half_float\fP 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "GLM_FUNC_QUALIFIER half glm::abs (\fBhalf\fP const & x)"
Returns the absolute value of a half-precision floating-point value 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_half_float\fP 
.RE
.PP

.SS "GLM_FUNC_QUALIFIER hvec2 glm::abs (\fBhvec2\fP const & x)"
Returns the absolute value of a half-precision floating-point two dimensional vector 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_half_float\fP 
.RE
.PP

.SS "GLM_FUNC_QUALIFIER hvec3 glm::abs (\fBhvec3\fP const & x)"
Returns the absolute value of a half-precision floating-point three dimensional vector 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_half_float\fP 
.RE
.PP

.SS "GLM_FUNC_QUALIFIER hvec4 glm::abs (\fBhvec4\fP const & x)"
Returns the absolute value of a half-precision floating-point four dimensional vector 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_half_float\fP 
.RE
.PP

.SS "GLM_FUNC_QUALIFIER \fBglm::half\fP glm::mix (\fBglm::half\fP const & x, \fBglm::half\fP const & y, bool const & a)"
Selects which vector each returned component comes from\&. For a component of  that is false, the corresponding component of x is returned\&. For a component of a that is true, the corresponding component of y is returned\&. Components of x and y that are not selected are allowed to be invalid floating point values and will have no effect on the results\&. Thus, this provides different functionality than genType mix(genType x, genType y, genType(a)) where a is a Boolean vector\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_half_float\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
