.TH "gtx_normal" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_normal \- GLM_GTX_normal
.PP
Compute the normal of a triangle\&.  

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > detail::tvec3< T > \fBglm::triangleNormal\fP (detail::tvec3< T > const &p1, detail::tvec3< T > const &p2, detail::tvec3< T > const &p3)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Compute the normal of a triangle\&. 

<\fBglm/gtx/normal\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename T > detail::tvec3<T> glm::triangleNormal (\fBdetail::tvec3\fP< T > const & p1, \fBdetail::tvec3\fP< T > const & p2, \fBdetail::tvec3\fP< T > const & p3)"
Computes triangle normal from triangle points\&. From GLM_GTX_normal extension\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
