.TH "gtx_wrap" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_wrap \- GLM_GTX_wrap
.PP
Wrapping mode of texture coordinates\&.  

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > genType \fBglm::clamp\fP (genType const &Texcoord)"
.br
.ti -1c
.RI "template<typename genType > genType \fBglm::repeat\fP (genType const &Texcoord)"
.br
.ti -1c
.RI "template<typename genType > genType \fBglm::mirrorRepeat\fP (genType const &Texcoord)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Wrapping mode of texture coordinates\&. 

<\fBglm/gtx/wrap\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename genType > genType glm::clamp (genType const & Texcoord)"
Simulate GL_CLAMP OpenGL wrap mode From GLM_GTX_wrap extension\&. 
.SS "template<typename genType > genType glm::mirrorRepeat (genType const & Texcoord)"
Simulate GL_MIRROR_REPEAT OpenGL wrap mode From GLM_GTX_wrap extension\&. 
.SS "template<typename genType > genType glm::repeat (genType const & Texcoord)"
Simulate GL_REPEAT OpenGL wrap mode From GLM_GTX_wrap extension\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
