.TH "gtx_int_10_10_10_2" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_int_10_10_10_2 \- GLM_GTX_int_10_10_10_2
.PP
Pack vector to 1010102 integers\&. Storage only\&.  

.SS "Functions"

.in +1c
.ti -1c
.RI "dword \fBglm::uint10_10_10_2_cast\fP (\fBglm::vec4\fP const &v)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Pack vector to 1010102 integers\&. Storage only\&. 

<\fBglm/gtx/int_10_10_10_2\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "GLM_FUNC_QUALIFIER dword glm::uint10_10_10_2_cast (\fBglm::vec4\fP const & v)"
From GLM_GTX_int_10_10_10_2 extension\&. Cast a vec4 to an u_10_10_10_2\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
