.TH "gtx_raw_data" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_raw_data \- GLM_GTX_raw_data
.PP
Projection of a vector to other one\&.  

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef uint8 \fBglm::byte\fP"
.br
.ti -1c
.RI "typedef uint16 \fBglm::word\fP"
.br
.ti -1c
.RI "typedef uint32 \fBglm::dword\fP"
.br
.ti -1c
.RI "typedef uint64 \fBglm::qword\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Projection of a vector to other one\&. 

<\fBglm/gtx/raw_data\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Typedef Documentation"
.PP 
.SS "typedef uint8 \fBglm::byte\fP"
Type for byte numbers\&. From GLM_GTX_raw_data extension\&. 
.SS "typedef uint32 \fBglm::dword\fP"
Type for dword numbers\&. From GLM_GTX_raw_data extension\&. 
.SS "typedef uint64 \fBglm::qword\fP"
Type for qword numbers\&. From GLM_GTX_raw_data extension\&. 
.SS "typedef uint16 \fBglm::word\fP"
Type for word numbers\&. From GLM_GTX_raw_data extension\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
