.TH "gtx_color_space_YCoCg" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_color_space_YCoCg \- GLM_GTX_color_space_YCoCg
.PP
RGB to YCoCg conversions and operations\&.  

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename valType > detail::tvec3< valType > \fBglm::rgb2YCoCg\fP (detail::tvec3< valType > const &rgbColor)"
.br
.ti -1c
.RI "template<typename valType > detail::tvec3< valType > \fBglm::YCoCg2rgb\fP (detail::tvec3< valType > const &YCoCgColor)"
.br
.ti -1c
.RI "template<typename valType > detail::tvec3< valType > \fBglm::rgb2YCoCgR\fP (detail::tvec3< valType > const &rgbColor)"
.br
.ti -1c
.RI "template<typename valType > detail::tvec3< valType > \fBglm::YCoCgR2rgb\fP (detail::tvec3< valType > const &YCoCgColor)"
.br
.in -1c
.SH "Detailed Description"
.PP 
RGB to YCoCg conversions and operations\&. 

<\fBglm/gtx/color_space_YCoCg\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename valType > detail::tvec3<valType> glm::rgb2YCoCg (\fBdetail::tvec3\fP< valType > const & rgbColor)"
Convert a color from RGB color space to YCoCg color space\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_color_space_YCoCg\fP 
.RE
.PP

.SS "template<typename valType > detail::tvec3<valType> glm::rgb2YCoCgR (\fBdetail::tvec3\fP< valType > const & rgbColor)"
Convert a color from RGB color space to YCoCgR color space\&. 
.PP
\fBSee also:\fP
.RS 4
'YCoCg-R: A Color Space with RGB Reversibility and Low Dynamic Range' 
.PP
\fBGLM_GTX_color_space_YCoCg\fP 
.RE
.PP

.SS "template<typename valType > detail::tvec3<valType> glm::YCoCg2rgb (\fBdetail::tvec3\fP< valType > const & YCoCgColor)"
Convert a color from YCoCg color space to RGB color space\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_color_space_YCoCg\fP 
.RE
.PP

.SS "template<typename valType > detail::tvec3<valType> glm::YCoCgR2rgb (\fBdetail::tvec3\fP< valType > const & YCoCgColor)"
Convert a color from YCoCgR color space to RGB color space\&. 
.PP
\fBSee also:\fP
.RS 4
'YCoCg-R: A Color Space with RGB Reversibility and Low Dynamic Range' 
.PP
\fBGLM_GTX_color_space_YCoCg\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
