.TH "gtx_std_based_type" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_std_based_type \- GLM_GTX_std_based_type
.PP
Adds vector types based on STL value types\&. <\fBglm/gtx/std_based_type\&.hpp\fP> need to be included to use these functionalities\&.  

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef detail::tvec2< std::size_t > \fBglm::size2\fP"
.br
.ti -1c
.RI "typedef detail::tvec3< std::size_t > \fBglm::size3\fP"
.br
.ti -1c
.RI "typedef detail::tvec4< std::size_t > \fBglm::size4\fP"
.br
.ti -1c
.RI "typedef detail::tvec2< std::size_t > \fBglm::size2_t\fP"
.br
.ti -1c
.RI "typedef detail::tvec3< std::size_t > \fBglm::size3_t\fP"
.br
.ti -1c
.RI "typedef detail::tvec4< std::size_t > \fBglm::size4_t\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Adds vector types based on STL value types\&. <\fBglm/gtx/std_based_type\&.hpp\fP> need to be included to use these functionalities\&. 


.SH "Typedef Documentation"
.PP 
.SS "typedef detail::tvec2<std::size_t> \fBglm::size2\fP"
Vector type based of two std::size_t components\&. 
.PP
\fBSee also:\fP
.RS 4
GLM_GTX_std_based_type 
.RE
.PP

.SS "typedef detail::tvec2<std::size_t> \fBglm::size2_t\fP"
Vector type based of two std::size_t components\&. 
.PP
\fBSee also:\fP
.RS 4
GLM_GTX_std_based_type 
.RE
.PP

.SS "typedef detail::tvec3<std::size_t> \fBglm::size3\fP"
Vector type based of three std::size_t components\&. 
.PP
\fBSee also:\fP
.RS 4
GLM_GTX_std_based_type 
.RE
.PP

.SS "typedef detail::tvec3<std::size_t> \fBglm::size3_t\fP"
Vector type based of three std::size_t components\&. 
.PP
\fBSee also:\fP
.RS 4
GLM_GTX_std_based_type 
.RE
.PP

.SS "typedef detail::tvec4<std::size_t> \fBglm::size4\fP"
Vector type based of four std::size_t components\&. 
.PP
\fBSee also:\fP
.RS 4
GLM_GTX_std_based_type 
.RE
.PP

.SS "typedef detail::tvec4<std::size_t> \fBglm::size4_t\fP"
Vector type based of four std::size_t components\&. 
.PP
\fBSee also:\fP
.RS 4
GLM_GTX_std_based_type 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
