.TH "gtx_mixed_product" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_mixed_product \- GLM_GTX_mixed_producte
.PP
Mixed product of 3 vectors\&.  

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename valType > valType \fBglm::mixedProduct\fP (detail::tvec3< valType > const &v1, detail::tvec3< valType > const &v2, detail::tvec3< valType > const &v3)"
.br
.RI "\fIMixed product of 3 vectors (from GLM_GTX_mixed_product extension) \fP"
.in -1c
.SH "Detailed Description"
.PP 
Mixed product of 3 vectors\&. 

<\fBglm/gtx/mixed_product\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
