.TH "gtx_vector_access" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_vector_access \- GLM_GTX_vector_access
.PP
Function to set values to vectors\&.  

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename valType > \fBvoid\fP \fBglm::set\fP (detail::tvec2< valType > &v, valType const &x, valType const &y)"
.br
.ti -1c
.RI "template<typename valType > \fBvoid\fP \fBglm::set\fP (detail::tvec3< valType > &v, valType const &x, valType const &y, valType const &z)"
.br
.ti -1c
.RI "template<typename valType > \fBvoid\fP \fBglm::set\fP (detail::tvec4< valType > &v, valType const &x, valType const &y, valType const &z, valType const &w)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Function to set values to vectors\&. 

<\fBglm/gtx/vector_access\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename valType > \fBvoid\fP glm::set (\fBdetail::tvec2\fP< valType > & v, valType const & x, valType const & y)"
Set values to a 2 components vector\&. From GLM_GTX_vector_access extension\&. 
.SS "template<typename valType > \fBvoid\fP glm::set (\fBdetail::tvec3\fP< valType > & v, valType const & x, valType const & y, valType const & z)"
Set values to a 3 components vector\&. From GLM_GTX_vector_access extension\&. 
.SS "template<typename valType > \fBvoid\fP glm::set (\fBdetail::tvec4\fP< valType > & v, valType const & x, valType const & y, valType const & z, valType const & w)"
Set values to a 4 components vector\&. From GLM_GTX_vector_access extension\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
