.TH "gtx_multiple" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_multiple \- GLM_GTX_multiple
.PP
Find the closest number of a number multiple of other number\&.  

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > genType \fBglm::higherMultiple\fP (genType const &Source, genType const &Multiple)"
.br
.ti -1c
.RI "template<typename genType > genType \fBglm::lowerMultiple\fP (genType const &Source, genType const &Multiple)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Find the closest number of a number multiple of other number\&. 

<\fBglm/gtx/multiple\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename genType > genType glm::higherMultiple (genType const & Source, genType const & Multiple)"
Higher Multiple number of Source\&. From GLM_GTX_multiple extension\&. 
.SS "template<typename genType > genType glm::lowerMultiple (genType const & Source, genType const & Multiple)"
Lower Multiple number of Source\&. From GLM_GTX_multiple extension\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
