.TH "gtx_log_base" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_log_base \- GLM_GTX_log_base
.PP
Logarithm for any base\&. base can be a vector or a scalar\&.  

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > genType \fBglm::log\fP (genType const &x, genType const &base)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Logarithm for any base\&. base can be a vector or a scalar\&. 

<\fBglm/gtx/log_base\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename genType > genType glm::log (genType const & x, genType const & base)"
Logarithm for any base\&. From GLM_GTX_log_base\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
