.TH "gtx_fast_trigonometry" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_fast_trigonometry \- GLM_GTX_fast_trigonometry
.PP
Fast but less accurate implementations of trigonometric functions\&.  

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > T \fBglm::fastSin\fP (const T &angle)"
.br
.ti -1c
.RI "template<typename T > T \fBglm::fastCos\fP (const T &angle)"
.br
.ti -1c
.RI "template<typename T > T \fBglm::fastTan\fP (const T &angle)"
.br
.ti -1c
.RI "template<typename T > T \fBglm::fastAsin\fP (const T &angle)"
.br
.ti -1c
.RI "template<typename T > T \fBglm::fastAcos\fP (const T &angle)"
.br
.ti -1c
.RI "template<typename T > T \fBglm::fastAtan\fP (const T &y, const T &x)"
.br
.ti -1c
.RI "template<typename T > T \fBglm::fastAtan\fP (const T &angle)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Fast but less accurate implementations of trigonometric functions\&. 

<\fBglm/gtx/fast_trigonometry\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename T > T glm::fastAcos (const T & angle)"
Faster than the common acos function but less accurate\&. Defined between -2pi and 2pi\&. From GLM_GTX_fast_trigonometry extension\&. 
.SS "template<typename T > T glm::fastAsin (const T & angle)"
Faster than the common asin function but less accurate\&. Defined between -2pi and 2pi\&. From GLM_GTX_fast_trigonometry extension\&. 
.SS "template<typename T > T glm::fastAtan (const T & y, const T & x)"
Faster than the common atan function but less accurate\&. Defined between -2pi and 2pi\&. From GLM_GTX_fast_trigonometry extension\&. 
.SS "template<typename T > T glm::fastAtan (const T & angle)"
Faster than the common atan function but less accurate\&. Defined between -2pi and 2pi\&. From GLM_GTX_fast_trigonometry extension\&. 
.SS "template<typename T > T glm::fastCos (const T & angle)"
Faster than the common cos function but less accurate\&. Defined between -2pi and 2pi\&. From GLM_GTX_fast_trigonometry extension\&. 
.SS "template<typename T > T glm::fastSin (const T & angle)"
Faster than the common sin function but less accurate\&. Defined between -2pi and 2pi\&. From GLM_GTX_fast_trigonometry extension\&. 
.SS "template<typename T > T glm::fastTan (const T & angle)"
Faster than the common tan function but less accurate\&. Defined between -2pi and 2pi\&. From GLM_GTX_fast_trigonometry extension\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
