.TH "gtx_matrix_operation" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_matrix_operation \- GLM_GTX_matrix_operation
.PP
Build diagonal matrices from vectors\&.  

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename valType > detail::tmat2x2< valType > \fBglm::diagonal2x2\fP (detail::tvec2< valType > const &v)"
.br
.ti -1c
.RI "template<typename valType > detail::tmat2x3< valType > \fBglm::diagonal2x3\fP (detail::tvec2< valType > const &v)"
.br
.ti -1c
.RI "template<typename valType > detail::tmat2x4< valType > \fBglm::diagonal2x4\fP (detail::tvec2< valType > const &v)"
.br
.ti -1c
.RI "template<typename valType > detail::tmat3x2< valType > \fBglm::diagonal3x2\fP (detail::tvec2< valType > const &v)"
.br
.ti -1c
.RI "template<typename valType > detail::tmat3x3< valType > \fBglm::diagonal3x3\fP (detail::tvec3< valType > const &v)"
.br
.ti -1c
.RI "template<typename valType > detail::tmat3x4< valType > \fBglm::diagonal3x4\fP (detail::tvec3< valType > const &v)"
.br
.ti -1c
.RI "template<typename valType > detail::tmat4x2< valType > \fBglm::diagonal4x2\fP (detail::tvec2< valType > const &v)"
.br
.ti -1c
.RI "template<typename valType > detail::tmat4x3< valType > \fBglm::diagonal4x3\fP (detail::tvec3< valType > const &v)"
.br
.ti -1c
.RI "template<typename valType > detail::tmat4x4< valType > \fBglm::diagonal4x4\fP (detail::tvec4< valType > const &v)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Build diagonal matrices from vectors\&. 

<\fBglm/gtx/matrix_operation\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename valType > detail::tmat2x2<valType> glm::diagonal2x2 (\fBdetail::tvec2\fP< valType > const & v)"
Build a diagonal matrix\&. From GLM_GTX_matrix_operation extension\&. 
.SS "template<typename valType > detail::tmat2x3<valType> glm::diagonal2x3 (\fBdetail::tvec2\fP< valType > const & v)"
Build a diagonal matrix\&. From GLM_GTX_matrix_operation extension\&. 
.SS "template<typename valType > detail::tmat2x4<valType> glm::diagonal2x4 (\fBdetail::tvec2\fP< valType > const & v)"
Build a diagonal matrix\&. From GLM_GTX_matrix_operation extension\&. 
.SS "template<typename valType > detail::tmat3x2<valType> glm::diagonal3x2 (\fBdetail::tvec2\fP< valType > const & v)"
Build a diagonal matrix\&. From GLM_GTX_matrix_operation extension\&. 
.SS "template<typename valType > detail::tmat3x3<valType> glm::diagonal3x3 (\fBdetail::tvec3\fP< valType > const & v)"
Build a diagonal matrix\&. From GLM_GTX_matrix_operation extension\&. 
.SS "template<typename valType > detail::tmat3x4<valType> glm::diagonal3x4 (\fBdetail::tvec3\fP< valType > const & v)"
Build a diagonal matrix\&. From GLM_GTX_matrix_operation extension\&. 
.SS "template<typename valType > detail::tmat4x2<valType> glm::diagonal4x2 (\fBdetail::tvec2\fP< valType > const & v)"
Build a diagonal matrix\&. From GLM_GTX_matrix_operation extension\&. 
.SS "template<typename valType > detail::tmat4x3<valType> glm::diagonal4x3 (\fBdetail::tvec3\fP< valType > const & v)"
Build a diagonal matrix\&. From GLM_GTX_matrix_operation extension\&. 
.SS "template<typename valType > detail::tmat4x4<valType> glm::diagonal4x4 (\fBdetail::tvec4\fP< valType > const & v)"
Build a diagonal matrix\&. From GLM_GTX_matrix_operation extension\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
