.TH "gtx_closest_point" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_closest_point \- GLM_GTX_closest_point
.PP
Find the point on a straight line which is the closet of a point\&.  

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > detail::tvec3< T > \fBglm::closestPointOnLine\fP (detail::tvec3< T > const &point, detail::tvec3< T > const &a, detail::tvec3< T > const &b)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Find the point on a straight line which is the closet of a point\&. 

<\fBglm/gtx/closest_point\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename T > detail::tvec3<T> glm::closestPointOnLine (\fBdetail::tvec3\fP< T > const & point, \fBdetail::tvec3\fP< T > const & a, \fBdetail::tvec3\fP< T > const & b)"
Find the point on a straight line which is the closet of a point\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_closest_point\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
