.TH "gtx_matrix_cross_product" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_matrix_cross_product \- GLM_GTX_matrix_cross_product
.PP
Build cross product matrices\&.  

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > detail::tmat3x3< T > \fBglm::matrixCross3\fP (detail::tvec3< T > const &x)"
.br
.ti -1c
.RI "template<typename T > detail::tmat4x4< T > \fBglm::matrixCross4\fP (detail::tvec3< T > const &x)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Build cross product matrices\&. 

<\fBglm/gtx/matrix_cross_product\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename T > detail::tmat3x3<T> glm::matrixCross3 (\fBdetail::tvec3\fP< T > const & x)"
Build a cross product matrix\&. From GLM_GTX_matrix_cross_product extension\&. 
.SS "template<typename T > detail::tmat4x4<T> glm::matrixCross4 (\fBdetail::tvec3\fP< T > const & x)"
Build a cross product matrix\&. From GLM_GTX_matrix_cross_product extension\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
