.TH "gtx_verbose_operator" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_verbose_operator \- GLM_GTX_verbose_operator
.PP
Use words to replace operators\&.  

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genTypeT , typename genTypeU > genTypeT \fBglm::add\fP (genTypeT const &a, genTypeU const &b)"
.br
.ti -1c
.RI "template<typename genTypeT , typename genTypeU > genTypeT \fBglm::sub\fP (genTypeT const &a, genTypeU const &b)"
.br
.ti -1c
.RI "template<typename genTypeT , typename genTypeU > genTypeT \fBglm::mul\fP (genTypeT const &a, genTypeU const &b)"
.br
.ti -1c
.RI "template<typename genTypeT , typename genTypeU > genTypeT \fBglm::div\fP (genTypeT const &a, genTypeU const &b)"
.br
.ti -1c
.RI "template<typename genTypeT , typename genTypeU , typename genTypeV > genTypeT \fBglm::mad\fP (genTypeT const &a, genTypeU const &b, genTypeV const &c)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Use words to replace operators\&. 

<\fBglm/gtx/verbose_operator\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename genTypeT , typename genTypeU > genTypeT glm::add (genTypeT const & a, genTypeU const & b)"
Addition of two values From GLM_GTX_verbose_operator extension\&. 
.SS "template<typename genTypeT , typename genTypeU > genTypeT glm::div (genTypeT const & a, genTypeU const & b)"
Division of two values From GLM_GTX_verbose_operator extension\&. 
.SS "template<typename genTypeT , typename genTypeU , typename genTypeV > genTypeT glm::mad (genTypeT const & a, genTypeU const & b, genTypeV const & c)"
Multiplication and addition of three values From GLM_GTX_verbose_operator extension\&. 
.SS "template<typename genTypeT , typename genTypeU > genTypeT glm::mul (genTypeT const & a, genTypeU const & b)"
Multiplication of two values From GLM_GTX_verbose_operator extension\&. 
.SS "template<typename genTypeT , typename genTypeU > genTypeT glm::sub (genTypeT const & a, genTypeU const & b)"
Substration of two values From GLM_GTX_verbose_operator extension\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
