.TH "gtx_vec1" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_vec1 \- GLM_GTX_vec1
.PP
Add vec1, ivec1, uvec1 and bvec1 types\&. <\fBglm/gtx/vec1\&.hpp\fP> need to be included to use these functionalities\&.  
Add vec1, ivec1, uvec1 and bvec1 types\&. <\fBglm/gtx/vec1\&.hpp\fP> need to be included to use these functionalities\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
