.TH "gtx_simd_vec4" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_simd_vec4 \- GLM_GTX_simd_vec4
.PP
SIMD implementation of vec4 type\&.  
SIMD implementation of vec4 type\&. 

<\fBglm/gtx/simd_vec4\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
