.TH "include/IA.hh" 3 "Tue Jun 9 2015" "Version 0.53" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/IA.hh \- \fBIA\fP class in the game\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'ACharacter\&.hh'\fP
.br
\fC#include 'Lua\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIA\fP"
.br
.RI "\fINPC class\&. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef enum \fBeDifficulty\fP \fBeDifficulty\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBeDifficulty\fP { \fBDUMMY\fP, \fBEASY\fP, \fBNORMAL\fP }"
.br
.RI "\fIAI's difficulty\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBIA\fP class in the game\&. 


.PP
\fBAuthor:\fP
.RS 4
ankirama 
.RE
.PP
\fBVersion:\fP
.RS 4
0\&.43 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
