.TH "IBomberman" 3 "Mon Jun 8 2015" "Version 0.53" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IBomberman \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBinitialize\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBupdate\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBdraw\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBgetName\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBgetPosition\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBgetDirection\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBgetSpeed\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBgetTexturePath\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBgetColor\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBgetR\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBgetG\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBgetB\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBgetScore\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBgetKeyLeft\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBgetKeyRight\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBgetKeyUp\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBgetKeyDown\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBgetKeyBomb\fP () const =0"
.br
.ti -1c
.RI "virtual void \fBgetBombs\fP () const =0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
