.TH "include/IntroState.hh" 3 "Tue Jun 9 2015" "Version 0.53" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/IntroState.hh \- First state of the bomberman\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'IGameState\&.hh'\fP
.br
\fC#include 'Button\&.hh'\fP
.br
\fC#include 'Error\&.hpp'\fP
.br
\fC#include 'GenerateText\&.hh'\fP
.br
\fC#include <map>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIntroState\fP"
.br
.RI "\fIFirst state of the bomberman\&. \fP"
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHEAD_IMG\fP   {std::string(IMG_PATH) + std::string('head\&.tga')}"
.br
.ti -1c
.RI "#define \fBBACK_PAUSE\fP   {std::string(IMG_PATH) + std::string('background/') + std::string('pause_background\&.tga')}"
.br
.ti -1c
.RI "#define \fBBACK_NAME\fP   {std::string(IMG_PATH) + std::string('texture/') + std::string('sauvegarde\&.tga')}"
.br
.in -1c
.SH "Detailed Description"
.PP 
First state of the bomberman\&. 


.PP
\fBAuthor:\fP
.RS 4
doT 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
