.TH "include/Lua.hh" 3 "Tue Jun 9 2015" "Version 0.53" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Lua.hh \- Linker lua cpp\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'lua\&.h'\fP
.br
\fC#include 'lauxlib\&.h'\fP
.br
\fC#include 'lualib\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLua\fP"
.br
.RI "\fIUsed to interpret lua code\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Linker lua cpp\&. 


.PP
\fBAuthor:\fP
.RS 4
ankirama 
.RE
.PP
\fBVersion:\fP
.RS 4
0\&.42 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
