.TH "Lua" 3 "Tue Jun 9 2015" "Version 0.53" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Lua \- Used to interpret lua code\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Lua\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLua\fP (const std::string &filename, int width, int height)"
.br
.RI "\fIconstructor \fP"
.ti -1c
.RI "\fB~Lua\fP ()"
.br
.RI "\fIdestructor \fP"
.ti -1c
.RI "int \fBgetPosition\fP (const char *map, int x, int y)"
.br
.RI "\fIexecute lua script \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "lua_State * \fBm_L\fP"
.br
.ti -1c
.RI "int \fBm_width\fP"
.br
.ti -1c
.RI "int \fBm_height\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Used to interpret lua code\&. 

It will allow us to communicate with our script and execute our AIs
.PP
\fBBug\fP
.RS 4
not generic, we can't use it to load/use a generic lua file\&. 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "Lua::Lua (const std::string & filename, int width, int height)"

.PP
constructor \fBLua\fP's constructor where we will init \fBLua\fP's object and load file / libs
.PP
\fBParameters:\fP
.RS 4
\fIfilename\fP : script we want to execute (like ai_dummy) 
.br
\fIwidth\fP : maze's width 
.br
\fIhegith\fP : maze's height 
.RE
.PP

.SS "Lua::~Lua ()"

.PP
destructor \fBLua\fP's destructor where we will close m_L 
.SH "Member Function Documentation"
.PP 
.SS "int Lua::getPosition (const char * map, int x, int y)"

.PP
execute lua script It will try to find the 'execute' function in lua file and call it\&. It will check the function's return (if it's a number or not)\&.
.PP
\fBParameters:\fP
.RS 4
\fImap\fP : the maze generated by \fBGenerateMaze\fP 
.br
\fIx\fP : the bomberman's current position in x 
.br
\fIy\fP : the bomberman's current position in y 
.RE
.PP
\fBReturns:\fP
.RS 4
: Next action to do (like left, put a bomb\&.\&.\&.) 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "int Lua::m_height\fC [private]\fP"
maze's height stored to AI 
.SS "lua_State* Lua::m_L\fC [private]\fP"
\fBLua\fP object used to use lua code 
.SS "int Lua::m_width\fC [private]\fP"
maze's width stored to AI 

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
