.TH "lua_Debug" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lua_Debug \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint\fP \fBevent\fP"
.br
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "const char * \fBnamewhat\fP"
.br
.ti -1c
.RI "const char * \fBwhat\fP"
.br
.ti -1c
.RI "const char * \fBsource\fP"
.br
.ti -1c
.RI "\fBint\fP \fBcurrentline\fP"
.br
.ti -1c
.RI "\fBint\fP \fBlinedefined\fP"
.br
.ti -1c
.RI "\fBint\fP \fBlastlinedefined\fP"
.br
.ti -1c
.RI "unsigned char \fBnups\fP"
.br
.ti -1c
.RI "unsigned char \fBnparams\fP"
.br
.ti -1c
.RI "char \fBisvararg\fP"
.br
.ti -1c
.RI "char \fBistailcall\fP"
.br
.ti -1c
.RI "char \fBshort_src\fP [LUA_IDSIZE]"
.br
.ti -1c
.RI "struct CallInfo * \fBi_ci\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
