.TH "md__r_e_a_d_m_e" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- README 
Ne pas oublier de mettre à jour (DL de l'intra) la bibliothèque de temps en temps
.PP
lien doc lib graphique: https://github.com/paulbaron/LibBombermanPackage
.PP
export a ajoute: export LD_LIBRARY_PATH=path_cpp_bomberman/lib/gdl/libs/
.PP
BONUS FRWERE:
.IP "\(bu" 2
Easter Egg - Konami Code 
.PP

