.TH "MultState" 3 "Tue Jun 9 2015" "Version 0.53" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MultState \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBIGameState\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBe_State\fP { \fBPLAY\fP, \fBEXIT\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInit\fP (\fBGameEngine\fP *)"
.br
.ti -1c
.RI "void \fBCleanup\fP ()"
.br
.ti -1c
.RI "void \fBPause\fP ()"
.br
.ti -1c
.RI "void \fBResume\fP (\fBGameEngine\fP *)"
.br
.ti -1c
.RI "void \fBUpdate\fP (\fBGameEngine\fP *)"
.br
.ti -1c
.RI "void \fBDraw\fP (\fBGameEngine\fP *)"
.br
.ti -1c
.RI "void \fBUp\fP (\fBGameEngine\fP *)"
.br
.ti -1c
.RI "void \fBDown\fP (\fBGameEngine\fP *)"
.br
.ti -1c
.RI "void \fBEnter\fP (\fBGameEngine\fP *)"
.br
.ti -1c
.RI "void \fBQuitState\fP (\fBGameEngine\fP *)"
.br
.ti -1c
.RI "void \fBQuit\fP (\fBGameEngine\fP *)"
.br
.ti -1c
.RI "void \fBmodKey\fP (const int, const int)"
.br
.ti -1c
.RI "std::vector< \fBButton\fP * >::iterator & \fBgetIterator\fP ()"
.br
.ti -1c
.RI "std::vector< \fBButton\fP * > & \fBgetVector\fP ()"
.br
.ti -1c
.RI "void \fBsetReleased\fP (bool)"
.br
.ti -1c
.RI "void \fBremoveLetter\fP (\fBGameEngine\fP *)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBMultState\fP * \fBInstance\fP ()"
.br
.in -1c
.SS "Private Types"

.in +1c
.ti -1c
.RI "typedef void(MultState::* \fBm_tabFun\fP) (\fBGameEngine\fP *)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBaddKey\fP (const int, m_tabFun)"
.br
.ti -1c
.RI "void \fBdelKey\fP (const int)"
.br
.ti -1c
.RI "void \fBdelAllKey\fP ()"
.br
.ti -1c
.RI "void \fBwriteName\fP (int const, \fBGameEngine\fP *)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBm_iterator\fP"
.br
.ti -1c
.RI "bool \fBm_released\fP"
.br
.ti -1c
.RI "\fBObject2D\fP * \fBm_background\fP"
.br
.ti -1c
.RI "\fBObject2D\fP * \fBm_backname1\fP"
.br
.ti -1c
.RI "\fBObject2D\fP * \fBm_backname2\fP"
.br
.ti -1c
.RI "\fBObject2D\fP * \fBm_head\fP"
.br
.ti -1c
.RI "std::string \fBm_name1\fP"
.br
.ti -1c
.RI "std::string \fBm_name2\fP"
.br
.ti -1c
.RI "std::map< int, m_tabFun > \fBm_map\fP"
.br
.ti -1c
.RI "std::vector< \fBButton\fP * > \fBm_button\fP"
.br
.ti -1c
.RI "std::vector< \fBButton\fP * >::iterator \fBm_it\fP"
.br
.ti -1c
.RI "std::vector< \fBGenerateText\fP * > \fBm_player\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static \fBMultState\fP \fBm_MultState\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
