.TH "Object2D" 3 "Tue Jun 9 2015" "Version 0.53" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Object2D \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBObject2D\fP (const std::string &, int, int, int)"
.br
.ti -1c
.RI "void \fBInit\fP (const float, const float, const float, const float)"
.br
.ti -1c
.RI "void \fBDraw\fP (gdl::BasicShader)"
.br
.ti -1c
.RI "void \fBTranslate\fP (glm::vec3 const &)"
.br
.ti -1c
.RI "void \fBRotate\fP (glm::vec3 const &, float)"
.br
.ti -1c
.RI "void \fBScale\fP (glm::vec3 const &)"
.br
.ti -1c
.RI "int \fBgetY\fP () const "
.br
.ti -1c
.RI "void \fBsetY\fP (const int, const int)"
.br
.ti -1c
.RI "glm::mat4 \fBgetTransformation\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::string \fBm_path\fP"
.br
.ti -1c
.RI "gdl::BasicShader \fBm_shader\fP"
.br
.ti -1c
.RI "gdl::Texture \fBm_texture\fP"
.br
.ti -1c
.RI "gdl::Geometry \fBm_geometry\fP"
.br
.ti -1c
.RI "glm::vec3 \fBm_position\fP"
.br
.ti -1c
.RI "glm::vec3 \fBm_rotation\fP"
.br
.ti -1c
.RI "glm::vec3 \fBm_scale\fP"
.br
.ti -1c
.RI "float \fBm_y\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
