.TH "lib/gdl/includes/glm/gtx/ocl_type.hpp" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/gdl/includes/glm/gtx/ocl_type.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./glm\&.hpp'\fP
.br
\fC#include 'ocl_type\&.inl'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGLM_GTX_ocl_type\fP   GLM_VERSION"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef detail::int8 \fBglm::gtx::cl_char\fP"
.br
.RI "\fI8bit signed integer\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::int16 \fBglm::gtx::cl_short\fP"
.br
.RI "\fI16bit signed integer\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::int32 \fBglm::gtx::cl_int\fP"
.br
.RI "\fI32bit signed integer\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::int64 \fBglm::gtx::cl_long\fP"
.br
.RI "\fI64bit signed integer\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::uint8 \fBglm::gtx::cl_uchar\fP"
.br
.RI "\fI8bit signed integer\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::uint16 \fBglm::gtx::cl_ushort\fP"
.br
.RI "\fI16bit signed integer\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::uint32 \fBglm::gtx::cl_uint\fP"
.br
.RI "\fI32bit signed integer\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::uint64 \fBglm::gtx::cl_ulong\fP"
.br
.RI "\fI64bit signed integer\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::float16 \fBglm::gtx::cl_half\fP"
.br
.RI "\fIHalf-precision floating-point scalar\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::float32 \fBglm::gtx::cl_float\fP"
.br
.RI "\fISingle-precision floating-point scalar\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::int8 \fBglm::gtx::cl_char1\fP"
.br
.RI "\fI8bit signed integer\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::int16 \fBglm::gtx::cl_short1\fP"
.br
.RI "\fI16bit signed integer\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::int32 \fBglm::gtx::cl_int1\fP"
.br
.RI "\fI32bit signed integer\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::int64 \fBglm::gtx::cl_long1\fP"
.br
.RI "\fI64bit signed integer\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::uint8 \fBglm::gtx::cl_uchar1\fP"
.br
.RI "\fI8bit signed integer\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::uint16 \fBglm::gtx::cl_ushort1\fP"
.br
.RI "\fI16bit signed integer\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::uint32 \fBglm::gtx::cl_uint1\fP"
.br
.RI "\fI32bit signed integer\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::uint64 \fBglm::gtx::cl_ulong1\fP"
.br
.RI "\fI64bit signed integer\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::float32 \fBglm::gtx::cl_float1\fP"
.br
.RI "\fISingle-precision floating-point scalar\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::tvec2< detail::int8 > \fBglm::gtx::cl_char2\fP"
.br
.RI "\fI8bit signed integer\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::tvec2< detail::int16 > \fBglm::gtx::cl_short2\fP"
.br
.RI "\fI16bit signed integer\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::tvec2< detail::int32 > \fBglm::gtx::cl_int2\fP"
.br
.RI "\fI32bit signed integer\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::tvec2< detail::int64 > \fBglm::gtx::cl_long2\fP"
.br
.RI "\fI64bit signed integer\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::tvec2< detail::uint8 > \fBglm::gtx::cl_uchar2\fP"
.br
.RI "\fI8bit signed integer\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::tvec2< detail::uint16 > \fBglm::gtx::cl_ushort2\fP"
.br
.RI "\fI16bit signed integer\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::tvec2< detail::uint32 > \fBglm::gtx::cl_uint2\fP"
.br
.RI "\fI32bit signed integer\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::tvec2< detail::uint64 > \fBglm::gtx::cl_ulong2\fP"
.br
.RI "\fI64bit signed integer\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::tvec2< detail::float32 > \fBglm::gtx::cl_float2\fP"
.br
.RI "\fISingle-precision floating-point scalar\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::tvec3< detail::int8 > \fBglm::gtx::cl_char3\fP"
.br
.RI "\fI8bit signed integer\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::tvec3< detail::int16 > \fBglm::gtx::cl_short3\fP"
.br
.RI "\fI16bit signed integer\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::tvec3< detail::int32 > \fBglm::gtx::cl_int3\fP"
.br
.RI "\fI32bit signed integer\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::tvec3< detail::int64 > \fBglm::gtx::cl_long3\fP"
.br
.RI "\fI64bit signed integer\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::tvec3< detail::uint8 > \fBglm::gtx::cl_uchar3\fP"
.br
.RI "\fI8bit signed integer\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::tvec3< detail::uint16 > \fBglm::gtx::cl_ushort3\fP"
.br
.RI "\fI16bit signed integer\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::tvec3< detail::uint32 > \fBglm::gtx::cl_uint3\fP"
.br
.RI "\fI32bit signed integer\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::tvec3< detail::uint64 > \fBglm::gtx::cl_ulong3\fP"
.br
.RI "\fI64bit signed integer\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::tvec3< detail::float32 > \fBglm::gtx::cl_float3\fP"
.br
.RI "\fISingle-precision floating-point scalar\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::tvec4< detail::int8 > \fBglm::gtx::cl_char4\fP"
.br
.RI "\fI8bit signed integer\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::tvec4< detail::int16 > \fBglm::gtx::cl_short4\fP"
.br
.RI "\fI16bit signed integer\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::tvec4< detail::int32 > \fBglm::gtx::cl_int4\fP"
.br
.RI "\fI32bit signed integer\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::tvec4< detail::int64 > \fBglm::gtx::cl_long4\fP"
.br
.RI "\fI64bit signed integer\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::tvec4< detail::uint8 > \fBglm::gtx::cl_uchar4\fP"
.br
.RI "\fI8bit signed integer\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::tvec4< detail::uint16 > \fBglm::gtx::cl_ushort4\fP"
.br
.RI "\fI16bit signed integer\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::tvec4< detail::uint32 > \fBglm::gtx::cl_uint4\fP"
.br
.RI "\fI32bit signed integer\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::tvec4< detail::uint64 > \fBglm::gtx::cl_ulong4\fP"
.br
.RI "\fI64bit signed integer\&. (from GLM_GTX_ocl_type extension) \fP"
.ti -1c
.RI "typedef detail::tvec4< detail::float32 > \fBglm::gtx::cl_float4\fP"
.br
.RI "\fISingle-precision floating-point scalar\&. (from GLM_GTX_ocl_type extension) \fP"
.in -1c
.SH "Detailed Description"
.PP 
OpenGL Mathematics (glm\&.g-truc\&.net)
.PP
Copyright (c) 2005 - 2013 G-Truc Creation (www\&.g-truc\&.net) Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the 'Software'), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
.PP
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software\&.
.PP
THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT\&. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE\&.
.PP
\fBGLM_GTX_ocl_type\fP
.PP
\fBDate:\fP
.RS 4
2009-05-07 / 2011-06-07 
.RE
.PP
\fBAuthor:\fP
.RS 4
Christophe Riccio
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM Core\fP (dependence) 
.PP
\fBGLM_GTX_extented_min_max\fP (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
