.TH "Player" 3 "Tue Jun 9 2015" "Version 0.53" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Player \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBACharacter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBgetKeyRight\fP () const "
.br
.ti -1c
.RI "int \fBgetKeyLeft\fP () const "
.br
.ti -1c
.RI "int \fBgetKeyUp\fP () const "
.br
.ti -1c
.RI "int \fBgetKeyDown\fP () const "
.br
.ti -1c
.RI "int \fBgetKeyBomb\fP () const "
.br
.ti -1c
.RI "void \fBsetKeyRight\fP (int)"
.br
.ti -1c
.RI "void \fBsetKeyLeft\fP (int)"
.br
.ti -1c
.RI "void \fBsetKeyUp\fP (int)"
.br
.ti -1c
.RI "void \fBsetKeyDown\fP (int)"
.br
.ti -1c
.RI "void \fBsetKeyBomb\fP (int)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::map< eActions, int > \fBm_input\fP"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
