.TH "include/Score.hh" 3 "Tue Jun 9 2015" "Version 0.53" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Score.hh \- save score into a file and load it  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <map>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'template_string\&.hh'\fP
.br
\fC#include 'split_map\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBScore\fP"
.br
.RI "\fISave/Load score\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
save score into a file and load it 


.PP
\fBAuthor:\fP
.RS 4
ankirama 
.RE
.PP
\fBVersion:\fP
.RS 4
0\&.42 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
