.TH "lib/gdl/includes/SDL_opengles.h" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/gdl/includes/SDL_opengles.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <GLES/gl\&.h>\fP
.br
\fC#include <GLES/glext\&.h>\fP
.br

.SH "Detailed Description"
.PP 
This is a simple file to encapsulate the OpenGL ES 2\&.0 API headers\&.
.PP
This is a simple file to encapsulate the OpenGL ES 1\&.X API headers\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
