.TH "SDL_Palette" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_Palette \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint\fP \fBncolors\fP"
.br
.ti -1c
.RI "\fBSDL_Color\fP * \fBcolors\fP"
.br
.ti -1c
.RI "\fBUint32\fP \fBversion\fP"
.br
.ti -1c
.RI "\fBint\fP \fBrefcount\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
