.TH "lib/gdl/includes/SDL_test_images.h" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/gdl/includes/SDL_test_images.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'SDL\&.h'\fP
.br
\fC#include 'begin_code\&.h'\fP
.br
\fC#include 'close_code\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBSDLTest_SurfaceImage_s\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBSDLTest_SurfaceImage_s\fP \fBSDLTest_SurfaceImage_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBSDL_Surface\fP * \fBSDLTest_ImageBlit\fP ()"
.br
.ti -1c
.RI "\fBSDL_Surface\fP * \fBSDLTest_ImageBlitColor\fP ()"
.br
.ti -1c
.RI "\fBSDL_Surface\fP * \fBSDLTest_ImageBlitAlpha\fP ()"
.br
.ti -1c
.RI "\fBSDL_Surface\fP * \fBSDLTest_ImageBlitBlendAdd\fP ()"
.br
.ti -1c
.RI "\fBSDL_Surface\fP * \fBSDLTest_ImageBlitBlend\fP ()"
.br
.ti -1c
.RI "\fBSDL_Surface\fP * \fBSDLTest_ImageBlitBlendMod\fP ()"
.br
.ti -1c
.RI "\fBSDL_Surface\fP * \fBSDLTest_ImageBlitBlendNone\fP ()"
.br
.ti -1c
.RI "\fBSDL_Surface\fP * \fBSDLTest_ImageBlitBlendAll\fP ()"
.br
.ti -1c
.RI "\fBSDL_Surface\fP * \fBSDLTest_ImageFace\fP ()"
.br
.ti -1c
.RI "\fBSDL_Surface\fP * \fBSDLTest_ImagePrimitives\fP ()"
.br
.ti -1c
.RI "\fBSDL_Surface\fP * \fBSDLTest_ImagePrimitivesBlend\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include file for SDL test framework\&.
.PP
This code is a part of the SDL2_test library, not the main SDL library\&. 
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBSDLTest_SurfaceImage_s\fP  \fBSDLTest_SurfaceImage_t\fP"
Type for test images\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
