.TH "lib/gdl/includes/SDL_test.h" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/gdl/includes/SDL_test.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'SDL\&.h'\fP
.br
\fC#include 'SDL_test_common\&.h'\fP
.br
\fC#include 'SDL_test_font\&.h'\fP
.br
\fC#include 'SDL_test_random\&.h'\fP
.br
\fC#include 'SDL_test_fuzzer\&.h'\fP
.br
\fC#include 'SDL_test_crc32\&.h'\fP
.br
\fC#include 'SDL_test_md5\&.h'\fP
.br
\fC#include 'SDL_test_log\&.h'\fP
.br
\fC#include 'SDL_test_assert\&.h'\fP
.br
\fC#include 'SDL_test_harness\&.h'\fP
.br
\fC#include 'SDL_test_images\&.h'\fP
.br
\fC#include 'SDL_test_compare\&.h'\fP
.br
\fC#include 'begin_code\&.h'\fP
.br
\fC#include 'close_code\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSDLTEST_MAX_LOGMESSAGE_LENGTH\fP   3584"
.br
.in -1c
.SH "Detailed Description"
.PP 
Include file for SDL test framework\&.
.PP
This code is a part of the SDL2_test library, not the main SDL library\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
