.TH "SDL_atomic_t" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_atomic_t \- A type representing an atomic integer value\&. It is a struct so people don't accidentally use numeric operations on it\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_atomic\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint\fP \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A type representing an atomic integer value\&. It is a struct so people don't accidentally use numeric operations on it\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
