.TH "SDL_MessageBoxColor" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_MessageBoxColor \- RGB value used in a message box color scheme\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_messagebox\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBUint8\fP \fBr\fP"
.br
.ti -1c
.RI "\fBUint8\fP \fBg\fP"
.br
.ti -1c
.RI "\fBUint8\fP \fBb\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
RGB value used in a message box color scheme\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
