.TH "SDL_WindowShapeMode" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_WindowShapeMode \- A struct that tags the \fBSDL_WindowShapeParams\fP union with an enum describing the type of its contents\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_shape\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBWindowShapeMode\fP \fBmode\fP"
.br
.RI "\fIThe mode of these window-shape parameters\&. \fP"
.ti -1c
.RI "\fBSDL_WindowShapeParams\fP \fBparameters\fP"
.br
.RI "\fIWindow-shape parameters\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A struct that tags the \fBSDL_WindowShapeParams\fP union with an enum describing the type of its contents\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
