.TH "lib/gdl/includes/SDL_system.h" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/gdl/includes/SDL_system.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'SDL_stdinc\&.h'\fP
.br
\fC#include 'SDL_keyboard\&.h'\fP
.br
\fC#include 'SDL_render\&.h'\fP
.br
\fC#include 'SDL_video\&.h'\fP
.br
\fC#include 'begin_code\&.h'\fP
.br
\fC#include 'close_code\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Include file for platform specific SDL API functions 
.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
