.TH "SDL_MessageBoxColorScheme" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_MessageBoxColorScheme \- A set of colors to use for message box dialogs\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_messagebox\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSDL_MessageBoxColor\fP \fBcolors\fP [SDL_MESSAGEBOX_COLOR_MAX]"
.br
.in -1c
.SH "Detailed Description"
.PP 
A set of colors to use for message box dialogs\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
