.TH "SDL_assert_data" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_assert_data \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint\fP \fBalways_ignore\fP"
.br
.ti -1c
.RI "unsigned \fBint\fP \fBtrigger_count\fP"
.br
.ti -1c
.RI "const char * \fBcondition\fP"
.br
.ti -1c
.RI "const char * \fBfilename\fP"
.br
.ti -1c
.RI "\fBint\fP \fBlinenum\fP"
.br
.ti -1c
.RI "const char * \fBfunction\fP"
.br
.ti -1c
.RI "const struct \fBSDL_assert_data\fP * \fBnext\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
