.TH "SDL_Rect" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_Rect \- A rectangle, with the origin at the upper left\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_rect\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint\fP \fBx\fP"
.br
.ti -1c
.RI "\fBint\fP \fBy\fP"
.br
.ti -1c
.RI "\fBint\fP \fBw\fP"
.br
.ti -1c
.RI "\fBint\fP \fBh\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A rectangle, with the origin at the upper left\&. 


.PP
\fBSee also:\fP
.RS 4
\fBSDL_RectEmpty\fP 
.PP
\fBSDL_RectEquals\fP 
.PP
\fBSDL_HasIntersection\fP 
.PP
\fBSDL_IntersectRect\fP 
.PP
\fBSDL_UnionRect\fP 
.PP
\fBSDL_EnclosePoints\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
