.TH "SDL_PixelFormat" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_PixelFormat \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_pixels\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBUint32\fP \fBformat\fP"
.br
.ti -1c
.RI "\fBSDL_Palette\fP * \fBpalette\fP"
.br
.ti -1c
.RI "\fBUint8\fP \fBBitsPerPixel\fP"
.br
.ti -1c
.RI "\fBUint8\fP \fBBytesPerPixel\fP"
.br
.ti -1c
.RI "\fBUint8\fP \fBpadding\fP [2]"
.br
.ti -1c
.RI "\fBUint32\fP \fBRmask\fP"
.br
.ti -1c
.RI "\fBUint32\fP \fBGmask\fP"
.br
.ti -1c
.RI "\fBUint32\fP \fBBmask\fP"
.br
.ti -1c
.RI "\fBUint32\fP \fBAmask\fP"
.br
.ti -1c
.RI "\fBUint8\fP \fBRloss\fP"
.br
.ti -1c
.RI "\fBUint8\fP \fBGloss\fP"
.br
.ti -1c
.RI "\fBUint8\fP \fBBloss\fP"
.br
.ti -1c
.RI "\fBUint8\fP \fBAloss\fP"
.br
.ti -1c
.RI "\fBUint8\fP \fBRshift\fP"
.br
.ti -1c
.RI "\fBUint8\fP \fBGshift\fP"
.br
.ti -1c
.RI "\fBUint8\fP \fBBshift\fP"
.br
.ti -1c
.RI "\fBUint8\fP \fBAshift\fP"
.br
.ti -1c
.RI "\fBint\fP \fBrefcount\fP"
.br
.ti -1c
.RI "struct \fBSDL_PixelFormat\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBNote:\fP
.RS 4
Everything in the pixel format structure is read-only\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
