.TH "lib/gdl/includes/SDL_config_minimal.h" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/gdl/includes/SDL_config_minimal.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'SDL_platform\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHAVE_STDARG_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STDDEF_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STDINT_H\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_AUDIO_DRIVER_DUMMY\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_JOYSTICK_DISABLED\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_HAPTIC_DISABLED\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_LOADSO_DISABLED\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_THREADS_DISABLED\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_TIMERS_DISABLED\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_DUMMY\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_FILESYSTEM_DUMMY\fP   1"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is the minimal configuration that can be used to build SDL\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
