.TH "SDL_WindowShapeParams" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_WindowShapeParams \- A union containing parameters for shaped windows\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_shape\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBUint8\fP \fBbinarizationCutoff\fP"
.br
.RI "\fIa cutoff alpha value for binarization of the window shape's alpha channel\&. \fP"
.ti -1c
.RI "\fBSDL_Color\fP \fBcolorKey\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A union containing parameters for shaped windows\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
