.TH "lib/gdl/includes/SDL_config_android.h" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/gdl/includes/SDL_config_android.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'SDL_platform\&.h'\fP
.br
\fC#include <stdarg\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHAVE_GCC_ATOMICS\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ALLOCA_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SYS_TYPES_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STDIO_H\fP   1"
.br
.ti -1c
.RI "#define \fBSTDC_HEADERS\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRING_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_INTTYPES_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STDINT_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_CTYPE_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MATH_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SIGNAL_H\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MALLOC\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_CALLOC\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_REALLOC\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_FREE\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ALLOCA\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_GETENV\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SETENV\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_PUTENV\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SETENV\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_UNSETENV\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_QSORT\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ABS\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_BCOPY\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MEMSET\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MEMCPY\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MEMMOVE\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_MEMCMP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRLEN\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRLCPY\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRLCAT\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRDUP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRCHR\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRRCHR\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRSTR\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRTOL\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRTOUL\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRTOLL\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRTOULL\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRTOD\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ATOI\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ATOF\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRCMP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRNCMP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRCASECMP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_STRNCASECMP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_VSSCANF\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_VSNPRINTF\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_M_PI\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ATAN\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ATAN2\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ACOS\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_ASIN\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_CEIL\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_COPYSIGN\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_COS\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_COSF\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_FABS\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_FLOOR\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_LOG\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_POW\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SCALBN\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SIN\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SINF\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SQRT\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SIGACTION\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SETJMP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_NANOSLEEP\fP   1"
.br
.ti -1c
.RI "#define \fBHAVE_SYSCONF\fP   1"
.br
.ti -1c
.RI "#define \fBSIZEOF_VOIDP\fP   4"
.br
.ti -1c
.RI "#define \fBSDL_AUDIO_DRIVER_ANDROID\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_AUDIO_DRIVER_DUMMY\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_JOYSTICK_ANDROID\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_HAPTIC_DUMMY\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_LOADSO_DLOPEN\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_THREAD_PTHREAD\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_THREAD_PTHREAD_RECURSIVE_MUTEX\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_TIMER_UNIX\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_DRIVER_ANDROID\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_OPENGL_ES\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_OPENGL_ES2\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_OPENGL_EGL\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_RENDER_OGL_ES\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_VIDEO_RENDER_OGL_ES2\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_POWER_ANDROID\fP   1"
.br
.ti -1c
.RI "#define \fBSDL_FILESYSTEM_DUMMY\fP   1"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is a configuration that can be used to build SDL for Android 
.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
