.TH "SDL_Finger" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_Finger \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "SDL_FingerID \fBid\fP"
.br
.ti -1c
.RI "float \fBx\fP"
.br
.ti -1c
.RI "float \fBy\fP"
.br
.ti -1c
.RI "float \fBpressure\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
