.TH "SDL_Point" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDL_Point \- The structure that defines a point\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_rect\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint\fP \fBx\fP"
.br
.ti -1c
.RI "\fBint\fP \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The structure that defines a point\&. 


.PP
\fBSee also:\fP
.RS 4
\fBSDL_EnclosePoints\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
