.TH "lib/gdl/includes/SDL_platform.h" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/gdl/includes/SDL_platform.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'begin_code\&.h'\fP
.br
\fC#include 'close_code\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "DECLSPEC const char *SDLCALL \fBSDL_GetPlatform\fP (\fBvoid\fP)"
.br
.RI "\fIGets the name of the platform\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Try to get a standard set of platform defines\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
