.TH "SDLTest_TestCaseReference" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDLTest_TestCaseReference \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_test_harness\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "SDLTest_TestCaseFp \fBtestCase\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "char * \fBdescription\fP"
.br
.ti -1c
.RI "\fBint\fP \fBenabled\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds information about a single test case\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
