.TH "SDLTest_TestSuiteReference" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDLTest_TestSuiteReference \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_test_harness\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "SDLTest_TestCaseSetUpFp \fBtestSetUp\fP"
.br
.ti -1c
.RI "const \fBSDLTest_TestCaseReference\fP ** \fBtestCases\fP"
.br
.ti -1c
.RI "SDLTest_TestCaseTearDownFp \fBtestTearDown\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds information about a test suite (multiple test cases)\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
