.TH "SDLTest_CommonState" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDLTest_CommonState \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char ** \fBargv\fP"
.br
.ti -1c
.RI "\fBUint32\fP \fBflags\fP"
.br
.ti -1c
.RI "\fBUint32\fP \fBverbose\fP"
.br
.ti -1c
.RI "const char * \fBvideodriver\fP"
.br
.ti -1c
.RI "\fBint\fP \fBdisplay\fP"
.br
.ti -1c
.RI "const char * \fBwindow_title\fP"
.br
.ti -1c
.RI "const char * \fBwindow_icon\fP"
.br
.ti -1c
.RI "\fBUint32\fP \fBwindow_flags\fP"
.br
.ti -1c
.RI "\fBint\fP \fBwindow_x\fP"
.br
.ti -1c
.RI "\fBint\fP \fBwindow_y\fP"
.br
.ti -1c
.RI "\fBint\fP \fBwindow_w\fP"
.br
.ti -1c
.RI "\fBint\fP \fBwindow_h\fP"
.br
.ti -1c
.RI "\fBint\fP \fBwindow_minW\fP"
.br
.ti -1c
.RI "\fBint\fP \fBwindow_minH\fP"
.br
.ti -1c
.RI "\fBint\fP \fBwindow_maxW\fP"
.br
.ti -1c
.RI "\fBint\fP \fBwindow_maxH\fP"
.br
.ti -1c
.RI "\fBint\fP \fBlogical_w\fP"
.br
.ti -1c
.RI "\fBint\fP \fBlogical_h\fP"
.br
.ti -1c
.RI "float \fBscale\fP"
.br
.ti -1c
.RI "\fBint\fP \fBdepth\fP"
.br
.ti -1c
.RI "\fBint\fP \fBrefresh_rate\fP"
.br
.ti -1c
.RI "\fBint\fP \fBnum_windows\fP"
.br
.ti -1c
.RI "\fBSDL_Window\fP ** \fBwindows\fP"
.br
.ti -1c
.RI "const char * \fBrenderdriver\fP"
.br
.ti -1c
.RI "\fBUint32\fP \fBrender_flags\fP"
.br
.ti -1c
.RI "SDL_bool \fBskip_renderer\fP"
.br
.ti -1c
.RI "SDL_Renderer ** \fBrenderers\fP"
.br
.ti -1c
.RI "SDL_Texture ** \fBtargets\fP"
.br
.ti -1c
.RI "const char * \fBaudiodriver\fP"
.br
.ti -1c
.RI "\fBSDL_AudioSpec\fP \fBaudiospec\fP"
.br
.ti -1c
.RI "\fBint\fP \fBgl_red_size\fP"
.br
.ti -1c
.RI "\fBint\fP \fBgl_green_size\fP"
.br
.ti -1c
.RI "\fBint\fP \fBgl_blue_size\fP"
.br
.ti -1c
.RI "\fBint\fP \fBgl_alpha_size\fP"
.br
.ti -1c
.RI "\fBint\fP \fBgl_buffer_size\fP"
.br
.ti -1c
.RI "\fBint\fP \fBgl_depth_size\fP"
.br
.ti -1c
.RI "\fBint\fP \fBgl_stencil_size\fP"
.br
.ti -1c
.RI "\fBint\fP \fBgl_double_buffer\fP"
.br
.ti -1c
.RI "\fBint\fP \fBgl_accum_red_size\fP"
.br
.ti -1c
.RI "\fBint\fP \fBgl_accum_green_size\fP"
.br
.ti -1c
.RI "\fBint\fP \fBgl_accum_blue_size\fP"
.br
.ti -1c
.RI "\fBint\fP \fBgl_accum_alpha_size\fP"
.br
.ti -1c
.RI "\fBint\fP \fBgl_stereo\fP"
.br
.ti -1c
.RI "\fBint\fP \fBgl_multisamplebuffers\fP"
.br
.ti -1c
.RI "\fBint\fP \fBgl_multisamplesamples\fP"
.br
.ti -1c
.RI "\fBint\fP \fBgl_retained_backing\fP"
.br
.ti -1c
.RI "\fBint\fP \fBgl_accelerated\fP"
.br
.ti -1c
.RI "\fBint\fP \fBgl_major_version\fP"
.br
.ti -1c
.RI "\fBint\fP \fBgl_minor_version\fP"
.br
.ti -1c
.RI "\fBint\fP \fBgl_debug\fP"
.br
.ti -1c
.RI "\fBint\fP \fBgl_profile_mask\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
