.TH "SDLTest_Crc32Context" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SDLTest_Crc32Context \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SDL_test_crc32\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "CrcUint32 \fBcrc32_table\fP [256]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Data structure for CRC32 (checksum) computation 

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
