.TH "todo" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 

.IP "\fBMember \fBglm::bitCount\fP (genIUType< T > const &Value)\fP" 1c
Clarify the declaration to specify that scalars are suported\&.  
.IP "\fBMember \fBglm::epsilon\fP ()\fP" 1c
Implement epsilon for half-precision floating point type\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_constants\fP  
.RE
.PP
.IP "\fBMember \fBglm::findLSB\fP (genIUType< T > const &Value)\fP" 1c
Clarify the declaration to specify that scalars are suported\&.  
.IP "\fBMember \fBglm::findMSB\fP (genIUType< T > const &Value)\fP" 1c
Clarify the declaration to specify that scalars are suported\&.  
.IP "\fBMember \fBglm::intBitsToFloat\fP (genIType const &value)\fP" 1c
Clarify this declaration, we don't need to actually specify the return type  
.IP "\fBMember \fBglm::outerProduct\fP (vecType const &c, vecType const &r)\fP" 1c
Clarify the declaration to specify that matType doesn't have to be provided when used\&.  
.IP "\fBMember \fBglm::uintBitsToFloat\fP (genUType const &value)\fP" 1c
Clarify this declaration, we don't need to actually specify the return type 
.PP

