.TH "lib/gdl/includes/glm/core/type_int.hpp" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/gdl/includes/glm/core/type_int.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'setup\&.hpp'\fP
.br
\fC#include '_detail\&.hpp'\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef signed short \fBglm::detail::lowp_int_t\fP"
.br
.ti -1c
.RI "typedef signed \fBint\fP \fBglm::detail::mediump_int_t\fP"
.br
.ti -1c
.RI "typedef sint64 \fBglm::detail::highp_int_t\fP"
.br
.ti -1c
.RI "typedef unsigned short \fBglm::detail::lowp_uint_t\fP"
.br
.ti -1c
.RI "typedef unsigned \fBint\fP \fBglm::detail::mediump_uint_t\fP"
.br
.ti -1c
.RI "typedef uint64 \fBglm::detail::highp_uint_t\fP"
.br
.ti -1c
.RI "typedef detail::lowp_int_t \fBglm::lowp_int\fP"
.br
.ti -1c
.RI "typedef detail::mediump_int_t \fBglm::mediump_int\fP"
.br
.ti -1c
.RI "typedef detail::highp_int_t \fBglm::highp_int\fP"
.br
.ti -1c
.RI "typedef detail::lowp_uint_t \fBglm::lowp_uint\fP"
.br
.ti -1c
.RI "typedef detail::mediump_uint_t \fBglm::mediump_uint\fP"
.br
.ti -1c
.RI "typedef detail::highp_uint_t \fBglm::highp_uint\fP"
.br
.ti -1c
.RI "typedef mediump_int \fBglm::int_t\fP"
.br
.ti -1c
.RI "typedef mediump_uint \fBglm::uint_t\fP"
.br
.ti -1c
.RI "typedef uint_t \fBglm::uint\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBglm::detail::GLM_DETAIL_IS_INT\fP (signed char)"
.br
.ti -1c
.RI "\fBglm::detail::GLM_DETAIL_IS_INT\fP (highp_int_t)"
.br
.ti -1c
.RI "\fBglm::detail::GLM_DETAIL_IS_UINT\fP (unsigned char)"
.br
.ti -1c
.RI "\fBglm::detail::GLM_DETAIL_IS_UINT\fP (highp_uint_t)"
.br
.in -1c
.SH "Detailed Description"
.PP 
OpenGL Mathematics (glm\&.g-truc\&.net)
.PP
Copyright (c) 2005 - 2013 G-Truc Creation (www\&.g-truc\&.net) Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the 'Software'), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
.PP
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software\&.
.PP
THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT\&. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE\&.
.PP
\fBGLM Core\fP
.PP
\fBDate:\fP
.RS 4
2008-08-22 / 2011-06-15 
.RE
.PP
\fBAuthor:\fP
.RS 4
Christophe Riccio 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
