.TH "lib/gdl/includes/glm/core/type.hpp" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/gdl/includes/glm/core/type.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'type_half\&.hpp'\fP
.br
\fC#include 'type_float\&.hpp'\fP
.br
\fC#include 'type_int\&.hpp'\fP
.br
\fC#include 'type_gentype\&.hpp'\fP
.br
\fC#include 'type_vec1\&.hpp'\fP
.br
\fC#include 'type_vec2\&.hpp'\fP
.br
\fC#include 'type_vec3\&.hpp'\fP
.br
\fC#include 'type_vec4\&.hpp'\fP
.br
\fC#include 'type_mat2x2\&.hpp'\fP
.br
\fC#include 'type_mat2x3\&.hpp'\fP
.br
\fC#include 'type_mat2x4\&.hpp'\fP
.br
\fC#include 'type_mat3x2\&.hpp'\fP
.br
\fC#include 'type_mat3x3\&.hpp'\fP
.br
\fC#include 'type_mat3x4\&.hpp'\fP
.br
\fC#include 'type_mat4x2\&.hpp'\fP
.br
\fC#include 'type_mat4x3\&.hpp'\fP
.br
\fC#include 'type_mat4x4\&.hpp'\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef mediump_vec2 \fBglm::vec2\fP"
.br
.ti -1c
.RI "typedef mediump_vec3 \fBglm::vec3\fP"
.br
.ti -1c
.RI "typedef mediump_vec4 \fBglm::vec4\fP"
.br
.ti -1c
.RI "typedef mediump_mat2x2 \fBglm::mat2x2\fP"
.br
.ti -1c
.RI "typedef mediump_mat2x3 \fBglm::mat2x3\fP"
.br
.ti -1c
.RI "typedef mediump_mat2x4 \fBglm::mat2x4\fP"
.br
.ti -1c
.RI "typedef mediump_mat3x2 \fBglm::mat3x2\fP"
.br
.ti -1c
.RI "typedef mediump_mat3x3 \fBglm::mat3x3\fP"
.br
.ti -1c
.RI "typedef mediump_mat3x4 \fBglm::mat3x4\fP"
.br
.ti -1c
.RI "typedef mediump_mat4x2 \fBglm::mat4x2\fP"
.br
.ti -1c
.RI "typedef mediump_mat4x3 \fBglm::mat4x3\fP"
.br
.ti -1c
.RI "typedef mediump_mat4x4 \fBglm::mat4x4\fP"
.br
.ti -1c
.RI "typedef mat2x2 \fBglm::mat2\fP"
.br
.ti -1c
.RI "typedef mat3x3 \fBglm::mat3\fP"
.br
.ti -1c
.RI "typedef mat4x4 \fBglm::mat4\fP"
.br
.ti -1c
.RI "typedef mediump_ivec2 \fBglm::ivec2\fP"
.br
.ti -1c
.RI "typedef mediump_ivec3 \fBglm::ivec3\fP"
.br
.ti -1c
.RI "typedef mediump_ivec4 \fBglm::ivec4\fP"
.br
.ti -1c
.RI "typedef mediump_uvec2 \fBglm::uvec2\fP"
.br
.ti -1c
.RI "typedef mediump_uvec3 \fBglm::uvec3\fP"
.br
.ti -1c
.RI "typedef mediump_uvec4 \fBglm::uvec4\fP"
.br
.ti -1c
.RI "typedef detail::tvec2< bool > \fBglm::bvec2\fP"
.br
.ti -1c
.RI "typedef detail::tvec3< bool > \fBglm::bvec3\fP"
.br
.ti -1c
.RI "typedef detail::tvec4< bool > \fBglm::bvec4\fP"
.br
.ti -1c
.RI "typedef detail::tvec2< double > \fBglm::dvec2\fP"
.br
.ti -1c
.RI "typedef detail::tvec3< double > \fBglm::dvec3\fP"
.br
.ti -1c
.RI "typedef detail::tvec4< double > \fBglm::dvec4\fP"
.br
.ti -1c
.RI "typedef detail::tmat2x2< double > \fBglm::dmat2\fP"
.br
.ti -1c
.RI "typedef detail::tmat3x3< double > \fBglm::dmat3\fP"
.br
.ti -1c
.RI "typedef detail::tmat4x4< double > \fBglm::dmat4\fP"
.br
.ti -1c
.RI "typedef detail::tmat2x2< double > \fBglm::dmat2x2\fP"
.br
.ti -1c
.RI "typedef detail::tmat2x3< double > \fBglm::dmat2x3\fP"
.br
.ti -1c
.RI "typedef detail::tmat2x4< double > \fBglm::dmat2x4\fP"
.br
.ti -1c
.RI "typedef detail::tmat3x2< double > \fBglm::dmat3x2\fP"
.br
.ti -1c
.RI "typedef detail::tmat3x3< double > \fBglm::dmat3x3\fP"
.br
.ti -1c
.RI "typedef detail::tmat3x4< double > \fBglm::dmat3x4\fP"
.br
.ti -1c
.RI "typedef detail::tmat4x2< double > \fBglm::dmat4x2\fP"
.br
.ti -1c
.RI "typedef detail::tmat4x3< double > \fBglm::dmat4x3\fP"
.br
.ti -1c
.RI "typedef detail::tmat4x4< double > \fBglm::dmat4x4\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
OpenGL Mathematics (glm\&.g-truc\&.net)
.PP
Copyright (c) 2005 - 2013 G-Truc Creation (www\&.g-truc\&.net) Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the 'Software'), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
.PP
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software\&.
.PP
THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT\&. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE\&.
.PP
\fBGLM Core\fP
.PP
\fBDate:\fP
.RS 4
2008-01-08 / 2011-06-15 
.RE
.PP
\fBAuthor:\fP
.RS 4
Christophe Riccio 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
