.TH "virtrev" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
virtrev \- VIRTREV Extensions
.PP
Extensions develop and maintain by Mathieu [matrem] Roumillac (http://www.opengl.org/discussion_boards/ubbthreads.php?ubb=showprofile&User=22660)\&.  

.SS "Modules"

.in +1c
.ti -1c
.RI "\fBGLM_VIRTREV_xstream: xml like output\fP"
.br
.RI "\fIStreaming vector and matrix in a xml way\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Extensions develop and maintain by Mathieu [matrem] Roumillac (http://www.opengl.org/discussion_boards/ubbthreads.php?ubb=showprofile&User=22660)\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
