.TH "virtrev_xstream" 3 "Sun Jun 7 2015" "Version 0.42" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
virtrev_xstream \- GLM_VIRTREV_xstream: xml like output
.PP
Streaming vector and matrix in a xml way\&.  
Streaming vector and matrix in a xml way\&. 

Include <\fBglm/virtrev/xstream\&.hpp\fP> for this functionality\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
