.TH "include/XmlLoad.hh" 3 "Tue Jun 9 2015" "Version 0.53" "cpp_bomberman" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/XmlLoad.hh \- load xml file  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'IA\&.hh'\fP
.br
\fC#include 'ACharacter\&.hh'\fP
.br
\fC#include 'Player\&.hh'\fP
.br
\fC#include 'Bomb\&.hh'\fP
.br
\fC#include 'tinyxml2\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBXmlLoad\fP"
.br
.RI "\fIload xml file \fP"
.in -1c
.SH "Detailed Description"
.PP 
load xml file 


.PP
\fBAuthor:\fP
.RS 4
ankirama 
.RE
.PP
\fBVersion:\fP
.RS 4
0\&.42 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for cpp_bomberman from the source code\&.
