//
// Created by Fabien Martinez on 21/05/15.
//

#ifndef CPP_BOMBERMAN_LUA_HH
#define CPP_BOMBERMAN_LUA_HH

/**
 * @file Lua.hh
 * @brief Linker lua cpp
 * @author ankirama
 * @version 0.42
 */

#include <string>
#include <iostream>
#include <vector>

extern "C" {
#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"
}

/**
 * @class Lua
 * @brief Used to interpret lua code
 *
 * It will allow us to communicate with our script and execute our AIs
 *
 * @bug not generic, we can't use it to load/use a generic lua file.
 */

class Lua {
public:
    /**
     * @brief constructor
     *
     * Lua's constructor where we will init Lua's object and load file / libs
     *
     * @param filename : script we want to execute (like ai_dummy)
     * @param width : maze's width
     * @param hegith : maze's height
     */
    Lua(const std::string& filename, int width, int height);

    /**
     * @brief destructor
     *
     * Lua's destructor where we will close m_L
     */
    ~Lua();

    /**
     * @brief execute lua script
     *
     * It will try to find the "execute" function in lua file and call it.
     * It will check the function's return (if it's a number or not).
     *
     * @param map : the maze generated by GenerateMaze
     * @param x   : the bomberman's current position in x
     * @param y   : the bomberman's current position in y
     * @return    : Next action to do (like left, put a bomb...)
     */
    int getPosition(const char *map, int x, int y);

private:
    lua_State   *m_L; /**< Lua object used to use lua code */
    int         m_width; /**< maze's width stored to AI */
    int         m_height; /**< maze's height stored to AI */
};

#endif //CPP_BOMBERMAN_LUA_HH
