.TH "includes/server/server.h" 3 "Tue Jun 9 2015" "Version 1.13" "psu_zappy" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/server/server.h \- server  

.SH SYNOPSIS
.br
.PP
\fC#include 'utils\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBs_server\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX_CLIENTS\fP   255"
.br
.ti -1c
.RI "#define \fBMAX_FD\fP   255"
.br
.ti -1c
.RI "#define \fBHOSTNAME\fP   'log\&.horizon\&.sao'"
.br
.ti -1c
.RI "#define \fBFD_FREE\fP   0"
.br
.ti -1c
.RI "#define \fBFD_CLIENT\fP   1"
.br
.ti -1c
.RI "#define \fBFD_SERVER\fP   2"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBs_server\fP \fBt_server\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
server 


.PP
\fBAuthor:\fP
.RS 4
ankirama 
.RE
.PP
\fBVersion:\fP
.RS 4
0\&.7 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for psu_zappy from the source code\&.
